-- Run this on the Postgres server to clear G3 Gate
CREATE USER billbook_runtime WITH PASSWORD '123';
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA acc TO billbook_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA con TO billbook_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA inv TO billbook_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA sal TO billbook_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA pur TO billbook_runtime;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA rpt TO billbook_runtime;

-- To ensure future tables get permissions:
ALTER DEFAULT PRIVILEGES IN SCHEMA acc GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO billbook_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA con GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO billbook_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA inv GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO billbook_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA sal GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO billbook_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA pur GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO billbook_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA rpt GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO billbook_runtime;
