// <auto-generated />
using System;
using Inventory.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inventory.Repository.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260801140000_AddRecosting")]
    partial class AddRecosting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inv")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Inventory.Entity.TableEntities.UomType", b =>
                {
                    b.Property<long>("UomTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UomTypeId"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("UomTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UomTypeSystemName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("UomTypeId");

                    b.HasIndex("OrgId");

                    b.HasIndex("OrgId", "UomTypeName")
                        .IsUnique();

                    b.HasIndex("OrgId", "UomTypeSystemName")
                        .IsUnique()
                        .HasDatabaseName("IX_UomTypes_SystemName")
                        .HasFilter("\"UomTypeSystemName\" IS NOT NULL");

                    b.HasIndex("OrgId", "DisplayOrder", "UomTypeName")
                        .HasDatabaseName("IX_UomTypes_Order");

                    b.ToTable("UomTypes", "inv");
                });
            modelBuilder.Entity("Inventory.Entity.TableEntities.UnitOfMeasure", b =>
                {
                    b.Property<long>("UomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UomId"));

                    b.Property<decimal>("ConversionToBase")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBaseUnit")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("UomCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("UomName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UomSystemName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("UomTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("UqcCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("UomId");

                    b.HasIndex("OrgId");

                    b.HasIndex("UomTypeId");

                    b.HasIndex("OrgId", "UomCode")
                        .IsUnique();

                    b.HasIndex("OrgId", "UomTypeId")
                        .IsUnique()
                        .HasDatabaseName("IX_UnitOfMeasures_BaseUnit")
                        .HasFilter("\"IsBaseUnit\" = true");

                    b.HasIndex("OrgId", "UomSystemName")
                        .IsUnique()
                        .HasDatabaseName("IX_UnitOfMeasures_SystemName")
                        .HasFilter("\"UomSystemName\" IS NOT NULL");

                    b.HasIndex("OrgId", "UomTypeId", "DisplayOrder", "UomCode")
                        .HasDatabaseName("IX_UnitOfMeasures_Order");

                    b.ToTable("UnitOfMeasures", "inv", t =>
                        {
                            t.HasCheckConstraint("chk_uom_base_factor", "\"IsBaseUnit\" = false OR \"ConversionToBase\" = 1");

                            t.HasCheckConstraint("chk_uom_conversion_positive", "\"ConversionToBase\" > 0");

                            t.HasCheckConstraint("chk_uom_decimals", "\"DecimalPlaces\" BETWEEN 0 AND 6");
                        });
                });
            modelBuilder.Entity("Inventory.Entity.TableEntities.ItemCategory", b =>
                {
                    b.Property<long>("ItemCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ItemCategoryId"));

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultCostingType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DefaultItemProfile")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<long?>("DefaultUomTypeId")
                        .HasColumnType("bigint");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<long?>("ParentCategoryId")
                        .HasColumnType("bigint");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("ItemCategoryId");

                    b.HasIndex("OrgId");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("OrgId", "CategoryCode")
                        .IsUnique();

                    b.HasIndex("OrgId", "ParentCategoryId", "DisplayOrder", "CategoryName")
                        .HasDatabaseName("IX_ItemCategories_Order");

                    b.ToTable("ItemCategories", "inv");
                });
            modelBuilder.Entity("Inventory.Entity.TableEntities.MetalPurity", b =>
                {
                    b.Property<long>("MetalPurityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MetalPurityId"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("MetalType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PurityFactor")
                        .HasColumnType("decimal(6,4)");

                    b.Property<string>("PurityName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PuritySystemName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("MetalPurityId");

                    b.HasIndex("OrgId");

                    b.HasIndex("OrgId", "MetalType", "PurityName")
                        .IsUnique();

                    b.HasIndex("OrgId", "MetalType", "DisplayOrder")
                        .HasDatabaseName("IX_MetalPurities_Order");

                    b.ToTable("MetalPurities", "inv", t =>
                        {
                            t.HasCheckConstraint("chk_purity_factor", "\"PurityFactor\" > 0 AND \"PurityFactor\" <= 1");
                        });
                });
            modelBuilder.Entity("Inventory.Entity.TableEntities.Item", b =>
                {
                    b.Property<long>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ItemId"));

                    b.Property<string>("CostingType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<long?>("DefaultWarehouseId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int?>("HsnSacCodeId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("InventoryUomId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBatchTracked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsExpiryTracked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPriceInclusiveOfTax")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPurchase")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReturnable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSales")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSerialTracked")
                        .HasColumnType("boolean");

                    b.Property<long?>("ItemCategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ItemProfile")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("LeadTimeDays")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MaxStockLevel")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("MinSalePrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MinStockLevel")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Mrp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrintName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("PurchaseUomId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("ReorderLevel")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("ReorderQuantity")
                        .HasColumnType("decimal(18,3)");

                    b.Property<long>("ReportUomId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("SalesPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("SalesUomId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("StandardCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<long?>("TaxGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("TaxPreference")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<bool>("TrackInventory")
                        .HasColumnType("boolean");

                    b.Property<long>("UomTypeId")
                        .HasColumnType("bigint");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("ItemId");

                    b.HasIndex("OrgId");

                    b.HasIndex("UomTypeId");

                    b.HasIndex("InventoryUomId");

                    b.HasIndex("ItemCategoryId");

                    b.HasIndex("OrgId", "ItemCode")
                        .IsUnique();

                    b.HasIndex("OrgId", "ItemName");

                    b.HasIndex("OrgId", "ItemCategoryId");

                    b.HasIndex("OrgId", "HsnSacCodeId");

                    b.HasIndex("OrgId", "DisplayOrder", "ItemName")
                        .HasDatabaseName("IX_Items_Order");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("IX_Items_Sales")
                        .HasFilter("\"IsSales\" = true");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("IX_Items_Purchase")
                        .HasFilter("\"IsPurchase\" = true");

                    b.ToTable("Items", "inv", t =>
                        {
                            t.HasCheckConstraint("chk_item_costing_tracking", "(\"TrackInventory\" = false AND \"CostingType\" = 'None') OR (\"TrackInventory\" = true AND \"CostingType\" <> 'None')");

                            t.HasCheckConstraint("chk_item_expiry_needs_batch", "\"IsExpiryTracked\" = false OR \"IsBatchTracked\" = true");

                            t.HasCheckConstraint("chk_item_fefo_tracking", "\"CostingType\" <> 'Fefo' OR (\"IsBatchTracked\" = true AND \"IsExpiryTracked\" = true)");

                            t.HasCheckConstraint("chk_item_min_sale_price", "\"MinSalePrice\" IS NULL OR \"SalesPrice\" IS NULL OR \"MinSalePrice\" <= \"SalesPrice\"");

                            t.HasCheckConstraint("chk_item_specific_tracking", "\"CostingType\" <> 'SpecificIdentification' OR \"IsSerialTracked\" = true");
                        });
                });
            modelBuilder.Entity("Inventory.Entity.TableEntities.ItemJewelleryDetails", b =>
                {
                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("GrossWeight")
                        .HasColumnType("decimal(12,3)");

                    b.Property<bool>("IsHallmarked")
                        .HasColumnType("boolean");

                    b.Property<string>("MakingChargeType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<decimal>("MakingChargeValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<long>("MetalPurityId")
                        .HasColumnType("bigint");

                    b.Property<string>("MetalType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("NetWeight")
                        .HasColumnType("decimal(12,3)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("StoneCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StoneWeight")
                        .HasColumnType("decimal(12,3)");

                    b.Property<decimal>("WastagePercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("ItemId");

                    b.HasIndex("OrgId");

                    b.HasIndex("MetalPurityId");

                    b.ToTable("ItemJewelleryDetails", "inv", t =>
                        {
                            t.HasCheckConstraint("chk_jewellery_making_percent", "\"MakingChargeType\" <> 'Percentage' OR \"MakingChargeValue\" <= 100");

                            t.HasCheckConstraint("chk_jewellery_weights", "\"NetWeight\" <= \"GrossWeight\" AND \"StoneWeight\" <= \"GrossWeight\"");
                        });
                });
            modelBuilder.Entity("Inventory.Entity.TableEntities.ItemPharmaDetails", b =>
                {
                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DosageForm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DrugSchedule")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("ExpiryAlertDays")
                        .HasColumnType("integer");

                    b.Property<string>("GenericName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsNarcotic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrescriptionRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("ManufacturerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MarketedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("MinExpiryDaysOnReceipt")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("PackSize")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ShelfLifeDays")
                        .HasColumnType("integer");

                    b.Property<string>("StorageCondition")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Strength")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("ItemId");

                    b.HasIndex("OrgId");

                    b.HasIndex("OrgId", "GenericName")
                        .HasDatabaseName("IX_ItemPharmaDetails_Generic");

                    b.ToTable("ItemPharmaDetails", "inv", t =>
                        {
                            t.HasCheckConstraint("chk_pharma_prescription", "\"DrugSchedule\" NOT IN ('H', 'H1', 'X') OR \"IsPrescriptionRequired\" = true");
                        });
                });
            modelBuilder.Entity("Inventory.Entity.TableEntities.ItemBarcode", b =>
                {
                    b.Property<long>("ItemBarcodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ItemBarcodeId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BarcodeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<long?>("UomId")
                        .HasColumnType("bigint");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("ItemBarcodeId");

                    b.HasIndex("OrgId");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrgId", "Barcode")
                        .IsUnique();

                    b.HasIndex("OrgId", "ItemId");

                    b.HasIndex("OrgId", "ItemId")
                        .IsUnique()
                        .HasDatabaseName("IX_ItemBarcodes_Primary")
                        .HasFilter("\"IsPrimary\" = true");

                    b.ToTable("ItemBarcodes", "inv");
                });
            modelBuilder.Entity("Inventory.Entity.TableEntities.Warehouse", b =>
                {
                    b.Property<long>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("WarehouseId"));

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContactPersonName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Gstin")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("StateId")
                        .HasColumnType("integer");

                    b.Property<string>("StorageType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("WarehouseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("WarehouseType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("WarehouseId");

                    b.HasIndex("OrgId");

                    b.HasIndex("OrgId", "WarehouseCode")
                        .IsUnique();

                    b.HasIndex("OrgId")
                        .IsUnique()
                        .HasDatabaseName("IX_Warehouses_Default")
                        .HasFilter("\"IsDefault\" = true");

                    b.HasIndex("OrgId", "DisplayOrder", "WarehouseName")
                        .HasDatabaseName("IX_Warehouses_Order");

                    b.ToTable("Warehouses", "inv");
                });
            modelBuilder.Entity("Shared.Kernel.Numbering.NumberingSeries", b =>
                {
                    b.Property<long>("NumberingSeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("NumberingSeriesId"));

                    b.Property<bool>("AllowManualOverride")
                        .HasColumnType("boolean");

                    b.Property<string>("BranchCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("FinancialYearFormat")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<bool>("IncludeBranchCode")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludeFinancialYear")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("LastResetOn")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<long>("NextNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("NumberLength")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("Prefix")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("ResetFrequency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("SeriesCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("SeriesFor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("SeriesName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SeriesSystemName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Separator")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<long>("StartNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Suffix")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("NumberingSeriesId");

                    b.HasIndex("OrgId");

                    b.HasIndex("OrgId", "SeriesName")
                        .IsUnique();

                    b.HasIndex("OrgId", "DisplayOrder", "SeriesName")
                        .HasDatabaseName("IX_NumberingSeries_Order");

                    b.HasIndex("OrgId", "SeriesCode")
                        .HasDatabaseName("IX_NumberingSeries_Lookup");

                    b.HasIndex("OrgId", "SeriesCode")
                        .IsUnique()
                        .HasDatabaseName("IX_NumberingSeries_Default")
                        .HasFilter("\"IsDefault\" = true");

                    b.HasIndex("OrgId", "SeriesSystemName")
                        .IsUnique()
                        .HasDatabaseName("IX_NumberingSeries_SystemName")
                        .HasFilter("\"SeriesSystemName\" IS NOT NULL");

                    b.ToTable("NumberingSeries", "acc", t =>
                        {
                            t.ExcludeFromMigrations();

                            t.HasCheckConstraint("chk_numbering_branch_code", "\"IncludeBranchCode\" = false OR \"BranchCode\" IS NOT NULL");

                            t.HasCheckConstraint("chk_numbering_counter", "\"NextNumber\" >= \"StartNumber\" AND \"NumberLength\" BETWEEN 1 AND 12");

                            t.HasCheckConstraint("chk_numbering_manual_override", "\"SeriesFor\" = 'Master' OR \"AllowManualOverride\" = false");
                        });
                });

            modelBuilder.Entity("Inventory.Entity.TableEntities.ItemStock", b =>
                {
                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastMovementAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QuantityOnHand")
                        .HasColumnType("decimal(18,3)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<decimal>("WeightedAverageCost")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("ItemId");

                    b.HasIndex("OrgId");

                    b.ToTable("ItemStock", "inv", t =>
                        {
                            t.HasCheckConstraint("chk_item_stock_non_negative", "\"QuantityOnHand\" >= 0 AND \"WeightedAverageCost\" >= 0");
                        });
                });

            modelBuilder.Entity("Inventory.Entity.TableEntities.StockMovement", b =>
                {
                    b.Property<long>("StockMovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("StockMovementId"));

                    b.Property<decimal>("ConversionFactor")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("EnteredQuantity")
                        .HasColumnType("decimal(18,3)");

                    b.Property<long>("EnteredUomId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("MovementDate")
                        .HasColumnType("date");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("ResultingWeightedAverageCost")
                        .HasColumnType("decimal(18,6)");

                    b.Property<long?>("ReturnsStockMovementId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SourceId")
                        .HasColumnType("bigint");

                    b.Property<long>("SourceLineId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceType")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("decimal(18,6)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<long?>("WarehouseId")
                        .HasColumnType("bigint");

                    b.HasKey("StockMovementId");

                    b.HasIndex("EnteredUomId");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrgId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("OrgId", "ItemId", "MovementDate")
                        .HasDatabaseName("IX_StockMovements_Item");

                    b.HasIndex("OrgId", "WarehouseId", "ItemId")
                        .HasDatabaseName("IX_StockMovements_Warehouse");

                    b.HasIndex("OrgId", "MovementDate")
                        .HasDatabaseName("IX_StockMovements_Date");

                    b.HasIndex("OrgId", "ReturnsStockMovementId")
                        .HasDatabaseName("IX_StockMovements_Returns")
                        .HasFilter("\"ReturnsStockMovementId\" IS NOT NULL");

                    b.HasIndex("OrgId", "SourceType", "SourceId", "SourceLineId")
                        .IsUnique()
                        .HasDatabaseName("IX_StockMovements_Source")
                        .HasFilter("\"SourceType\" IS NOT NULL");

                    b.ToTable("StockMovements", "inv", t =>
                        {
                            t.HasCheckConstraint("chk_movement_conversion", "\"Quantity\" = ROUND(\"EnteredQuantity\" * \"ConversionFactor\", 3)");

                            t.HasCheckConstraint("chk_movement_cost_non_negative", "(\"UnitCost\" IS NULL OR \"UnitCost\" >= 0) AND (\"TotalCost\" IS NULL OR \"TotalCost\" >= 0)");

                            t.HasCheckConstraint("chk_movement_quantity_positive", "\"Quantity\" > 0 AND \"EnteredQuantity\" > 0 AND \"ConversionFactor\" > 0");

                            t.HasCheckConstraint("chk_movement_source", "(\"SourceType\" IS NULL AND \"SourceId\" IS NULL) OR (\"SourceType\" IS NOT NULL AND \"SourceId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Inventory.Entity.TableEntities.ItemBatch", b =>
                {
                    b.Property<long>("ItemBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ItemBatchId"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("ManufactureDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Mrp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SupplierBatchNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("ItemBatchId");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrgId");

                    b.HasIndex("OrgId", "ItemId", "BatchNumber")
                        .IsUnique();

                    b.HasIndex("OrgId", "ItemId", "ExpiryDate")
                        .HasDatabaseName("IX_ItemBatches_Expiry")
                        .HasFilter("\"ExpiryDate\" IS NOT NULL");

                    b.ToTable("ItemBatches", "inv", t =>
                        {
                            t.HasCheckConstraint("chk_batch_dates", "\"ManufactureDate\" IS NULL OR \"ExpiryDate\" IS NULL OR \"ExpiryDate\" >= \"ManufactureDate\"");
                        });
                });

            modelBuilder.Entity("Inventory.Entity.TableEntities.ItemSerial", b =>
                {
                    b.Property<long>("ItemSerialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ItemSerialId"));

                    b.Property<long?>("CostLayerId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("HallmarkNumber")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<long?>("IssuedMovementId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ItemBatchId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<long?>("ReceivedMovementId")
                        .HasColumnType("bigint");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<long?>("WarehouseId")
                        .HasColumnType("bigint");

                    b.HasKey("ItemSerialId");

                    b.HasIndex("ItemBatchId");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrgId");

                    b.HasIndex("OrgId", "HallmarkNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_ItemSerials_Huid")
                        .HasFilter("\"HallmarkNumber\" IS NOT NULL");

                    b.HasIndex("OrgId", "ItemId", "SerialNumber")
                        .IsUnique();

                    b.HasIndex("OrgId", "ItemId", "Status")
                        .HasDatabaseName("IX_ItemSerials_Status");

                    b.ToTable("ItemSerials", "inv");
                });

            modelBuilder.Entity("Inventory.Entity.TableEntities.CostLayer", b =>
                {
                    b.Property<long>("CostLayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CostLayerId"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ExpiresOn")
                        .HasColumnType("date");

                    b.Property<long?>("ItemBatchId")
                        .HasColumnType("bigint");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("OriginalQuantity")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateOnly>("ReceivedOn")
                        .HasColumnType("date");

                    b.Property<decimal>("RemainingQuantity")
                        .HasColumnType("decimal(18,3)");

                    b.Property<long>("StockMovementId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,6)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("CostLayerId");

                    b.HasIndex("ItemBatchId");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrgId");

                    b.HasIndex("StockMovementId");

                    b.HasIndex("OrgId", "StockMovementId")
                        .IsUnique();

                    b.HasIndex("OrgId", "ItemId", "ReceivedOn")
                        .HasDatabaseName("IX_CostLayers_Fifo")
                        .HasFilter("\"RemainingQuantity\" > 0");

                    b.HasIndex("OrgId", "ItemId", "ExpiresOn")
                        .HasDatabaseName("IX_CostLayers_Fefo")
                        .HasFilter("\"RemainingQuantity\" > 0 AND \"ExpiresOn\" IS NOT NULL");

                    b.ToTable("CostLayers", "inv", t =>
                        {
                            t.HasCheckConstraint("chk_layer_remaining", "\"RemainingQuantity\" >= 0 AND \"RemainingQuantity\" <= \"OriginalQuantity\" AND \"OriginalQuantity\" > 0 AND \"UnitCost\" >= 0");
                        });
                });

            modelBuilder.Entity("Inventory.Entity.TableEntities.CostLayerConsumption", b =>
                {
                    b.Property<long>("CostLayerConsumptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CostLayerConsumptionId"));

                    b.Property<long>("CostLayerId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");
                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid?>("RecostingBatchId")
                        .HasColumnType("uuid");

                    b.Property<long>("StockMovementId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("SupersededAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,6)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("CostLayerConsumptionId");

                    b.HasIndex("CostLayerId");

                    b.HasIndex("OrgId");

                    b.HasIndex("StockMovementId");

                    b.HasIndex("OrgId", "StockMovementId", "CostLayerId")
                        .IsUnique()
                        .HasDatabaseName("IX_CostLayerConsumptions_Allocation")
                        .HasFilter("\"SupersededAt\" IS NULL");

                    b.HasIndex("OrgId", "StockMovementId")
                        .HasDatabaseName("IX_CostLayerConsumptions_Movement");

                    b.HasIndex("OrgId", "CostLayerId")
                        .HasDatabaseName("IX_CostLayerConsumptions_Layer");

                    b.ToTable("CostLayerConsumptions", "inv", t =>
                        {
                            t.HasCheckConstraint("chk_consumption_amounts", "\"Quantity\" > 0 AND \"UnitCost\" >= 0 AND \"TotalCost\" >= 0");
                        });
                });

            modelBuilder.Entity("Inventory.Entity.TableEntities.RecostingAdjustment", b =>
                {
                    b.Property<long>("RecostingAdjustmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RecostingAdjustmentId"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Delta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("NewCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PreviousCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("RecostingBatchId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RunAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("StockMovementId")
                        .HasColumnType("bigint");

                    b.Property<long>("TriggerStockMovementId")
                        .HasColumnType("bigint");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("RecostingAdjustmentId");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrgId");

                    b.HasIndex("StockMovementId");

                    b.HasIndex("OrgId", "RecostingBatchId")
                        .HasDatabaseName("IX_RecostingAdjustments_Batch");

                    b.HasIndex("OrgId", "ItemId", "RunAt")
                        .HasDatabaseName("IX_RecostingAdjustments_Item");

                    b.HasIndex("OrgId", "StockMovementId")
                        .HasDatabaseName("IX_RecostingAdjustments_Movement");

                    b.ToTable("RecostingAdjustments", "inv", t =>
                        {
                            t.HasCheckConstraint("chk_recosting_delta", "\"Delta\" = \"NewCost\" - \"PreviousCost\"");
                        });
                });

            modelBuilder.Entity("Inventory.Entity.TableEntities.UnitOfMeasure", b =>
                {
                    b.HasOne("Inventory.Entity.TableEntities.UomType", null)
                        .WithMany()
                        .HasForeignKey("UomTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
            modelBuilder.Entity("Inventory.Entity.TableEntities.ItemCategory", b =>
                {
                    b.HasOne("Inventory.Entity.TableEntities.ItemCategory", null)
                        .WithMany()
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
            modelBuilder.Entity("Inventory.Entity.TableEntities.Item", b =>
                {
                    b.HasOne("Inventory.Entity.TableEntities.UomType", null)
                        .WithMany()
                        .HasForeignKey("UomTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Inventory.Entity.TableEntities.UnitOfMeasure", null)
                        .WithMany()
                        .HasForeignKey("InventoryUomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Inventory.Entity.TableEntities.ItemCategory", null)
                        .WithMany()
                        .HasForeignKey("ItemCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
            modelBuilder.Entity("Inventory.Entity.TableEntities.ItemJewelleryDetails", b =>
                {
                    b.HasOne("Inventory.Entity.TableEntities.Item", null)
                        .WithOne()
                        .HasForeignKey("Inventory.Entity.TableEntities.ItemJewelleryDetails", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inventory.Entity.TableEntities.MetalPurity", null)
                        .WithMany()
                        .HasForeignKey("MetalPurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
            modelBuilder.Entity("Inventory.Entity.TableEntities.ItemPharmaDetails", b =>
                {
                    b.HasOne("Inventory.Entity.TableEntities.Item", null)
                        .WithOne()
                        .HasForeignKey("Inventory.Entity.TableEntities.ItemPharmaDetails", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
            modelBuilder.Entity("Inventory.Entity.TableEntities.ItemBarcode", b =>
                {
                    b.HasOne("Inventory.Entity.TableEntities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
            modelBuilder.Entity("Inventory.Entity.TableEntities.ItemStock", b =>
                {
                    b.HasOne("Inventory.Entity.TableEntities.Item", null)
                        .WithOne()
                        .HasForeignKey("Inventory.Entity.TableEntities.ItemStock", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory.Entity.TableEntities.StockMovement", b =>
                {
                    b.HasOne("Inventory.Entity.TableEntities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Inventory.Entity.TableEntities.UnitOfMeasure", null)
                        .WithMany()
                        .HasForeignKey("EnteredUomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Inventory.Entity.TableEntities.Warehouse", null)
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Inventory.Entity.TableEntities.ItemBatch", b =>
                {
                    b.HasOne("Inventory.Entity.TableEntities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory.Entity.TableEntities.ItemSerial", b =>
                {
                    b.HasOne("Inventory.Entity.TableEntities.ItemBatch", null)
                        .WithMany()
                        .HasForeignKey("ItemBatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Inventory.Entity.TableEntities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory.Entity.TableEntities.CostLayer", b =>
                {
                    b.HasOne("Inventory.Entity.TableEntities.ItemBatch", null)
                        .WithMany()
                        .HasForeignKey("ItemBatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Inventory.Entity.TableEntities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Inventory.Entity.TableEntities.StockMovement", null)
                        .WithMany()
                        .HasForeignKey("StockMovementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory.Entity.TableEntities.CostLayerConsumption", b =>
                {
                    b.HasOne("Inventory.Entity.TableEntities.CostLayer", null)
                        .WithMany()
                        .HasForeignKey("CostLayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Inventory.Entity.TableEntities.StockMovement", null)
                        .WithMany()
                        .HasForeignKey("StockMovementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Inventory.Entity.TableEntities.RecostingAdjustment", b =>
                {
                    b.HasOne("Inventory.Entity.TableEntities.Item", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Inventory.Entity.TableEntities.StockMovement", null)
                        .WithMany()
                        .HasForeignKey("StockMovementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

#pragma warning restore 612, 618
        }
    }
}
