// <auto-generated />
using System;
using Accounting.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Accounting.Repository.Migrations
{
    [DbContext(typeof(AccountingDbContext))]
    [Migration("20260804033824_AddOpeningBalances")]
    partial class AddOpeningBalances
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("acc")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Accounting.Entity.TableEntities.Account", b =>
                {
                    b.Property<long>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AccountId"));

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AccountSystemName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("AccountTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBank")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsContra")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsJE")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLock")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPayment")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPurchase")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSales")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<long?>("ParentAccountId")
                        .HasColumnType("bigint");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("AccountId");

                    b.HasIndex("OrgId");

                    b.HasIndex("ParentAccountId");

                    b.HasIndex("OrgId", "AccountCode")
                        .IsUnique();

                    b.HasIndex("OrgId", "AccountSystemName")
                        .IsUnique()
                        .HasDatabaseName("IX_Accounts_SystemName")
                        .HasFilter("\"AccountSystemName\" IS NOT NULL");

                    b.HasIndex("OrgId", "AccountTypeId");

                    b.HasIndex(new[] { "OrgId" }, "IX_Accounts_Bank")
                        .HasFilter("\"IsBank\" = true");

                    b.HasIndex(new[] { "OrgId" }, "IX_Accounts_Purchase")
                        .HasFilter("\"IsPurchase\" = true");

                    b.HasIndex(new[] { "OrgId" }, "IX_Accounts_Sales")
                        .HasFilter("\"IsSales\" = true");

                    b.ToTable("Accounts", "acc");
                });

            modelBuilder.Entity("Accounting.Entity.TableEntities.Journal", b =>
                {
                    b.Property<long>("JournalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("JournalId"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateOnly>("JournalDate")
                        .HasColumnType("date");

                    b.Property<string>("JournalNo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Memo")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PostedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("ReversedByJournalId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReversesJournalId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SourceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TransactionTypeCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("JournalId");

                    b.HasIndex("OrgId");

                    b.HasIndex("ReversedByJournalId");

                    b.HasIndex("ReversesJournalId");

                    b.HasIndex("OrgId", "JournalDate");

                    b.HasIndex("OrgId", "JournalNo")
                        .IsUnique()
                        .HasDatabaseName("IX_Journals_Number")
                        .HasFilter("\"JournalNo\" IS NOT NULL");

                    b.HasIndex("OrgId", "TransactionTypeCode", "SourceId");

                    b.ToTable("Journals", "acc", t =>
                        {
                            t.HasCheckConstraint("chk_journal_number_on_post", "(\"Status\" = 'Draft' AND \"JournalNo\" IS NULL) OR (\"Status\" <> 'Draft' AND \"JournalNo\" IS NOT NULL)");

                            t.HasCheckConstraint("chk_journal_posted_stamp", "(\"Status\" = 'Draft') = (\"PostedAt\" IS NULL)");

                            t.HasCheckConstraint("chk_journal_rate_positive", "\"ExchangeRate\" > 0");

                            t.HasCheckConstraint("chk_journal_reversal_distinct", "\"ReversesJournalId\" IS NULL OR \"ReversesJournalId\" <> \"JournalId\"");
                        });
                });

            modelBuilder.Entity("Accounting.Entity.TableEntities.JournalDetail", b =>
                {
                    b.Property<long>("JournalDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("JournalDetailId"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CreditAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CreditAmountBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DebitAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DebitAmountBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("JournalId")
                        .HasColumnType("bigint");

                    b.Property<string>("LineMemo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<long?>("ReversedByJournalDetailId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ReversesJournalDetailId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SubAccountId")
                        .HasColumnType("bigint");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("JournalDetailId");

                    b.HasIndex("AccountId");

                    b.HasIndex("OrgId");

                    b.HasIndex("ReversedByJournalDetailId");

                    b.HasIndex("ReversesJournalDetailId");

                    b.HasIndex("SubAccountId");

                    b.HasIndex("JournalId", "LineNumber")
                        .IsUnique();

                    b.ToTable("JournalDetails", "acc", t =>
                        {
                            t.HasCheckConstraint("chk_journal_detail_exclusive", "(\"DebitAmount\" > 0 AND \"CreditAmount\" = 0) OR (\"CreditAmount\" > 0 AND \"DebitAmount\" = 0)");

                            t.HasCheckConstraint("chk_journal_detail_non_negative", "\"DebitAmount\" >= 0 AND \"CreditAmount\" >= 0 AND \"DebitAmountBase\" >= 0 AND \"CreditAmountBase\" >= 0");
                        });
                });

            modelBuilder.Entity("Accounting.Entity.TableEntities.JournalLedger", b =>
                {
                    b.Property<long>("LedgerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LedgerId"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ContactId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CreditAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CreditAmountBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("DebitAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DebitAmountBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18,8)");

                    b.Property<long?>("JournalId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("LedgerDate")
                        .HasColumnType("date");

                    b.Property<int>("LedgerSourceId")
                        .HasColumnType("integer");

                    b.Property<int>("LedgerTypeId")
                        .HasColumnType("integer");

                    b.Property<long?>("MappingTransactionId")
                        .HasColumnType("bigint");

                    b.Property<string>("MappingTransactionTypeCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<long?>("SourceDocumentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SubAccountId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("TaxExchangeRate")
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("TransactionDesc")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("TransactionDetailId")
                        .HasColumnType("bigint");

                    b.Property<long>("TransactionId")
                        .HasColumnType("bigint");

                    b.Property<string>("TransactionTypeCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("LedgerId");

                    b.HasIndex("AccountId");

                    b.HasIndex("OrgId");

                    b.HasIndex("SubAccountId");

                    b.HasIndex("OrgId", "ContactId");

                    b.HasIndex("OrgId", "LedgerDate");

                    b.HasIndex("OrgId", "SubAccountId");

                    b.HasIndex("OrgId", "AccountId", "LedgerDate");

                    b.HasIndex("OrgId", "MappingTransactionTypeCode", "MappingTransactionId")
                        .HasDatabaseName("IX_JournalLedger_Mapping");

                    b.HasIndex("OrgId", "TransactionTypeCode", "TransactionId", "TransactionDetailId", "LedgerTypeId")
                        .HasDatabaseName("IX_JournalLedger_Posting");

                    b.ToTable("JournalLedger", "acc", t =>
                        {
                            t.HasCheckConstraint("chk_ledger_base_exclusive", "\"DebitAmountBase\" = 0 OR \"CreditAmountBase\" = 0");

                            t.HasCheckConstraint("chk_ledger_exclusive", "(\"DebitAmount\" = 0) <> (\"CreditAmount\" = 0)");

                            t.HasCheckConstraint("chk_ledger_non_negative", "\"DebitAmount\" >= 0 AND \"CreditAmount\" >= 0 AND \"DebitAmountBase\" >= 0 AND \"CreditAmountBase\" >= 0");
                        });
                });

            modelBuilder.Entity("Accounting.Entity.TableEntities.OpeningBalance", b =>
                {
                    b.Property<long>("OpeningBalanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OpeningBalanceId"));

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FinalizedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Memo")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TransactionNo")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("OpeningBalanceId");

                    b.HasIndex("OrgId")
                        .IsUnique()
                        .HasDatabaseName("IX_OpeningBalances_Org");

                    b.ToTable("OpeningBalances", "acc", t =>
                        {
                            t.HasCheckConstraint("chk_opening_finalized_stamp", "(\"Status\" = 'Draft') = (\"FinalizedAt\" IS NULL)");

                            t.HasCheckConstraint("chk_opening_number_on_finalize", "(\"Status\" = 'Draft' AND \"TransactionNo\" IS NULL) OR (\"Status\" <> 'Draft' AND \"TransactionNo\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Accounting.Entity.TableEntities.OpeningBalanceLine", b =>
                {
                    b.Property<long>("OpeningBalanceLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("OpeningBalanceLineId"));

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ContactId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CreditAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DebitAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("DocumentDate")
                        .HasColumnType("date");

                    b.Property<string>("DocumentReference")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<long?>("ItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("LineMemo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<string>("LineType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<long>("OpeningBalanceId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("decimal(18,6)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("OpeningBalanceLineId");

                    b.HasIndex("AccountId");

                    b.HasIndex("OrgId");

                    b.HasIndex("OpeningBalanceId", "LineNumber")
                        .IsUnique();

                    b.HasIndex("OrgId", "ContactId");

                    b.HasIndex("OrgId", "ItemId");

                    b.ToTable("OpeningBalanceLines", "acc", t =>
                        {
                            t.HasCheckConstraint("chk_opening_line_exclusive", "\"LineType\" = 'Item' OR (\"DebitAmount\" > 0 AND \"CreditAmount\" = 0) OR (\"CreditAmount\" > 0 AND \"DebitAmount\" = 0)");

                            t.HasCheckConstraint("chk_opening_line_item_shape", "(\"LineType\" = 'Item' AND \"Quantity\" > 0 AND \"UnitCost\" >= 0 AND \"DebitAmount\" = 0 AND \"CreditAmount\" = 0) OR (\"LineType\" <> 'Item' AND \"Quantity\" IS NULL AND \"UnitCost\" IS NULL)");

                            t.HasCheckConstraint("chk_opening_line_names_its_subject", "(\"LineType\" = 'GlAccount' AND \"AccountId\" IS NOT NULL AND \"ContactId\" IS NULL AND \"ItemId\" IS NULL) OR (\"LineType\" IN ('ContactReceivable', 'ContactPayable') AND \"ContactId\" IS NOT NULL AND \"AccountId\" IS NULL AND \"ItemId\" IS NULL) OR (\"LineType\" = 'Item' AND \"ItemId\" IS NOT NULL AND \"AccountId\" IS NULL AND \"ContactId\" IS NULL)");

                            t.HasCheckConstraint("chk_opening_line_non_negative", "\"DebitAmount\" >= 0 AND \"CreditAmount\" >= 0");
                        });
                });

            modelBuilder.Entity("Accounting.Entity.TableEntities.PaymentTerm", b =>
                {
                    b.Property<long>("PaymentTermId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PaymentTermId"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("DiscountDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int?>("DueDayOfMonth")
                        .HasColumnType("integer");

                    b.Property<int>("DueDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPurchase")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSales")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("TermName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TermSystemName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TermType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("PaymentTermId");

                    b.HasIndex("OrgId");

                    b.HasIndex("OrgId", "TermName")
                        .IsUnique();

                    b.HasIndex("OrgId", "TermSystemName")
                        .IsUnique()
                        .HasDatabaseName("IX_PaymentTerms_SystemName")
                        .HasFilter("\"TermSystemName\" IS NOT NULL");

                    b.HasIndex("OrgId", "DisplayOrder", "TermName")
                        .HasDatabaseName("IX_PaymentTerms_Order");

                    b.HasIndex(new[] { "OrgId" }, "IX_PaymentTerms_Default")
                        .IsUnique()
                        .HasFilter("\"IsDefault\" = true");

                    b.HasIndex(new[] { "OrgId" }, "IX_PaymentTerms_Purchase")
                        .HasFilter("\"IsPurchase\" = true");

                    b.HasIndex(new[] { "OrgId" }, "IX_PaymentTerms_Sales")
                        .HasFilter("\"IsSales\" = true");

                    b.ToTable("PaymentTerms", "acc", t =>
                        {
                            t.HasCheckConstraint("chk_term_applicability", "\"IsSales\" = true OR \"IsPurchase\" = true");

                            t.HasCheckConstraint("chk_term_day_of_month", "(\"TermType\" = 'DayOfNextMonth' AND \"DueDayOfMonth\" IS NOT NULL) OR (\"TermType\" <> 'DayOfNextMonth' AND \"DueDayOfMonth\" IS NULL)");

                            t.HasCheckConstraint("chk_term_discount_days", "\"DiscountPercent\" = 0 OR \"DiscountDays\" > 0");

                            t.HasCheckConstraint("chk_term_discount_window", "\"TermType\" <> 'Net' OR \"DiscountDays\" <= \"DueDays\"");

                            t.HasCheckConstraint("chk_term_due_on_receipt", "\"TermType\" <> 'DueOnReceipt' OR \"DueDays\" = 0");
                        });
                });

            modelBuilder.Entity("Accounting.Entity.TableEntities.PeriodLock", b =>
                {
                    b.Property<long>("PeriodLockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PeriodLockId"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("LockedUpto")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("PeriodLockId");

                    b.HasIndex("OrgId");

                    b.HasIndex("OrgId", "RoleId")
                        .IsUnique();

                    b.ToTable("PeriodLocks", "acc");
                });

            modelBuilder.Entity("Accounting.Entity.TableEntities.SubAccount", b =>
                {
                    b.Property<long>("SubAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SubAccountId"));

                    b.Property<long>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<int>("AccountTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("ReferenceId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SubAccountName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TaxComponent")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("SubAccountId");

                    b.HasIndex("OrgId");

                    b.HasIndex("OrgId", "Purpose")
                        .HasDatabaseName("IX_SubAccounts_Purpose");

                    b.HasIndex("OrgId", "ReferenceType", "ReferenceId");

                    b.HasIndex("AccountId", "ReferenceType", "ReferenceId", "TaxComponent", "Purpose")
                        .IsUnique();

                    b.ToTable("SubAccounts", "acc");
                });

            modelBuilder.Entity("Accounting.Entity.TableEntities.TaxMaster", b =>
                {
                    b.Property<long>("TaxMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TaxMasterId"));

                    b.Property<decimal>("CessRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("CgstRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<decimal>("IgstRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPurchase")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSales")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SgstRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<long>("TaxGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("TaxName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TaxSystemName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("TotalRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("TaxMasterId");

                    b.HasIndex("OrgId");

                    b.HasIndex("OrgId", "EffectiveFrom", "EffectiveTo");

                    b.HasIndex("OrgId", "TaxGroupId", "EffectiveFrom");

                    b.HasIndex(new[] { "OrgId" }, "IX_TaxMasters_Purchase")
                        .HasFilter("\"IsPurchase\" = true");

                    b.HasIndex(new[] { "OrgId" }, "IX_TaxMasters_Sales")
                        .HasFilter("\"IsSales\" = true");

                    b.ToTable("TaxMasters", "acc", t =>
                        {
                            t.HasCheckConstraint("chk_tax_applicability", "\"IsSales\" = true OR \"IsPurchase\" = true");

                            t.HasCheckConstraint("chk_tax_effective_range", "\"EffectiveTo\" IS NULL OR \"EffectiveTo\" >= \"EffectiveFrom\"");

                            t.HasCheckConstraint("chk_tax_split", "\"CgstRate\" = \"SgstRate\" AND \"CgstRate\" + \"SgstRate\" = \"TotalRate\" AND \"IgstRate\" = \"TotalRate\"");
                        });
                });

            modelBuilder.Entity("Shared.Kernel.Numbering.NumberingSeries", b =>
                {
                    b.Property<long>("NumberingSeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("NumberingSeriesId"));

                    b.Property<bool>("AllowManualOverride")
                        .HasColumnType("boolean");

                    b.Property<string>("BranchCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("FinancialYearFormat")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<bool>("IncludeBranchCode")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludeFinancialYear")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("LastResetOn")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<long>("NextNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("NumberLength")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("Prefix")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("ResetFrequency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Separator")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("SeriesCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("SeriesFor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("SeriesName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SeriesSystemName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<long>("StartNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Suffix")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("NumberingSeriesId");

                    b.HasIndex("OrgId");

                    b.HasIndex("OrgId", "SeriesCode")
                        .IsUnique()
                        .HasDatabaseName("IX_NumberingSeries_Default")
                        .HasFilter("\"IsDefault\" = true");

                    b.HasIndex("OrgId", "SeriesName")
                        .IsUnique();

                    b.HasIndex("OrgId", "SeriesSystemName")
                        .IsUnique()
                        .HasDatabaseName("IX_NumberingSeries_SystemName")
                        .HasFilter("\"SeriesSystemName\" IS NOT NULL");

                    b.HasIndex("OrgId", "DisplayOrder", "SeriesName")
                        .HasDatabaseName("IX_NumberingSeries_Order");

                    b.ToTable("NumberingSeries", "acc", t =>
                        {
                            t.HasCheckConstraint("chk_numbering_branch_code", "\"IncludeBranchCode\" = false OR \"BranchCode\" IS NOT NULL");

                            t.HasCheckConstraint("chk_numbering_counter", "\"NextNumber\" >= \"StartNumber\" AND \"NumberLength\" BETWEEN 1 AND 12");

                            t.HasCheckConstraint("chk_numbering_manual_override", "\"SeriesFor\" = 'Master' OR \"AllowManualOverride\" = false");
                        });
                });

            modelBuilder.Entity("Accounting.Entity.TableEntities.Account", b =>
                {
                    b.HasOne("Accounting.Entity.TableEntities.Account", null)
                        .WithMany()
                        .HasForeignKey("ParentAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Accounting.Entity.TableEntities.Journal", b =>
                {
                    b.HasOne("Accounting.Entity.TableEntities.Journal", null)
                        .WithMany()
                        .HasForeignKey("ReversedByJournalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Accounting.Entity.TableEntities.Journal", null)
                        .WithMany()
                        .HasForeignKey("ReversesJournalId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Accounting.Entity.TableEntities.JournalDetail", b =>
                {
                    b.HasOne("Accounting.Entity.TableEntities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Accounting.Entity.TableEntities.Journal", null)
                        .WithMany()
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accounting.Entity.TableEntities.JournalDetail", null)
                        .WithMany()
                        .HasForeignKey("ReversedByJournalDetailId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Accounting.Entity.TableEntities.JournalDetail", null)
                        .WithMany()
                        .HasForeignKey("ReversesJournalDetailId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Accounting.Entity.TableEntities.SubAccount", null)
                        .WithMany()
                        .HasForeignKey("SubAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Accounting.Entity.TableEntities.JournalLedger", b =>
                {
                    b.HasOne("Accounting.Entity.TableEntities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Accounting.Entity.TableEntities.SubAccount", null)
                        .WithMany()
                        .HasForeignKey("SubAccountId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Accounting.Entity.TableEntities.OpeningBalanceLine", b =>
                {
                    b.HasOne("Accounting.Entity.TableEntities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Accounting.Entity.TableEntities.OpeningBalance", null)
                        .WithMany()
                        .HasForeignKey("OpeningBalanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Accounting.Entity.TableEntities.SubAccount", b =>
                {
                    b.HasOne("Accounting.Entity.TableEntities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
