using Preventive.Entity.Enums;

namespace Preventive.Api.Services;

/// <summary>
/// A plan's due dates (S7, TK-67). Pure. Month-based frequencies count from the
/// start date rather than from the last due date, so a plan starting on the
/// 31st falls on the 30th in April and back on the 31st in May rather than
/// drifting to the 28th for ever.
/// </summary>
public static class Recurrence
{
    public static int MonthsPer(Frequency frequency) => frequency switch
    {
        Frequency.Monthly => 1,
        Frequency.Quarterly => 3,
        Frequency.HalfYearly => 6,
        Frequency.Yearly => 12,
        _ => 0,
    };

    /// <summary>The <paramref name="n"/>th due date, counting the start date as the 0th.</summary>
    public static DateOnly Occurrence(DateOnly start, Frequency frequency, int interval, int n) => frequency switch
    {
        Frequency.Daily => start.AddDays(n * interval),
        Frequency.Weekly => start.AddDays(7 * n * interval),
        _ => start.AddMonths(MonthsPer(frequency) * interval * n),
    };

    /// <summary>The first due date strictly after <paramref name="after"/>.</summary>
    public static DateOnly NextAfter(DateOnly start, Frequency frequency, int interval, DateOnly after)
    {
        if (after < start)
        {
            return start;
        }

        // Jump close, then step: a daily plan years old should not loop day by day.
        int n = frequency switch
        {
            Frequency.Daily => (after.DayNumber - start.DayNumber) / interval,
            Frequency.Weekly => (after.DayNumber - start.DayNumber) / (7 * interval),
            _ => (((after.Year - start.Year) * 12) + after.Month - start.Month) / (MonthsPer(frequency) * interval),
        };

        n = Math.Max(0, n - 1);
        DateOnly due = Occurrence(start, frequency, interval, n);
        while (due <= after)
        {
            due = Occurrence(start, frequency, interval, ++n);
        }

        return due;
    }

    /// <summary>Whether an occurrence falling due on <paramref name="due"/> should be generated by <paramref name="today"/>.</summary>
    public static bool IsInWindow(DateOnly due, int leadDays, DateOnly? endDate, DateOnly today) =>
        (endDate is null || due <= endDate) && due.AddDays(-leadDays) <= today;
}
