using Master.Entity.TableEntities;

namespace Master.Repository.SeedData;

public static class GeographySeed
{
    public static IReadOnlyList<Currency> GetCurrencies()
    {
        return new List<Currency>
        {
            new Currency { CurrencyId = 1, Code = "INR", Name = "Indian rupee", Symbol = "₹", Format = "##,##,##,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 2, Code = "USD", Name = "United States dollar", Symbol = "$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 3, Code = "GBP", Name = "British pound", Symbol = "£", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 4, Code = "AED", Name = "United Arab Emirates dirham", Symbol = "إ.د", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 5, Code = "SGD", Name = "Singapore dollar", Symbol = "$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 6, Code = "AAD", Name = "Antarctican dollar", Symbol = "$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 7, Code = "AFN", Name = "Afghan afghani", Symbol = "؋", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 8, Code = "ALL", Name = "Albanian lek", Symbol = "Lek", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 9, Code = "AMD", Name = "Armenian dram", Symbol = "֏", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 10, Code = "ANG", Name = "Netherlands Antillean guilder", Symbol = "ƒ", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 11, Code = "AOA", Name = "Angolan kwanza", Symbol = "Kz", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 12, Code = "ARS", Name = "Argentine peso", Symbol = "$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 13, Code = "AUD", Name = "Australian dollar", Symbol = "$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 14, Code = "AWG", Name = "Aruban florin", Symbol = "ƒ", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 15, Code = "AZN", Name = "Azerbaijani manat", Symbol = "m", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 16, Code = "BAM", Name = "Bosnia and Herzegovina convertible mark", Symbol = "KM", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 17, Code = "BBD", Name = "Barbadian dollar", Symbol = "Bds$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 18, Code = "BDT", Name = "Bangladeshi taka", Symbol = "৳", Format = "##,##,##,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 19, Code = "BHD", Name = "Bahraini dinar", Symbol = ".د.ب", Format = "###,###,##0.000", DecimalPlaces = 3 },
            new Currency { CurrencyId = 20, Code = "BIF", Name = "Burundian franc", Symbol = "FBu", Format = "###,###,##0", DecimalPlaces = 0 },
            new Currency { CurrencyId = 21, Code = "BMD", Name = "Bermudian dollar", Symbol = "$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 22, Code = "BND", Name = "Brunei dollar", Symbol = "B$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 23, Code = "BOB", Name = "Bolivian boliviano", Symbol = "Bs.", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 24, Code = "BRL", Name = "Brazilian real", Symbol = "R$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 25, Code = "BSD", Name = "Bahamian dollar", Symbol = "B$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 26, Code = "BTN", Name = "Bhutanese ngultrum", Symbol = "Nu.", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 27, Code = "BWP", Name = "Botswana pula", Symbol = "P", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 28, Code = "BYN", Name = "Belarusian ruble", Symbol = "Br", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 29, Code = "BZD", Name = "Belize dollar", Symbol = "$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 30, Code = "CAD", Name = "Canadian dollar", Symbol = "$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 31, Code = "CDF", Name = "Congolese Franc", Symbol = "FC", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 32, Code = "CHF", Name = "Swiss franc", Symbol = "CHf", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 33, Code = "CLP", Name = "Chilean peso", Symbol = "$", Format = "###,###,##0", DecimalPlaces = 0 },
            new Currency { CurrencyId = 34, Code = "CNY", Name = "Chinese yuan", Symbol = "¥", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 35, Code = "COP", Name = "Colombian peso", Symbol = "$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 36, Code = "CRC", Name = "Costa Rican colón", Symbol = "₡", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 37, Code = "CUP", Name = "Cuban peso", Symbol = "$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 38, Code = "CVE", Name = "Cape Verdean escudo", Symbol = "$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 39, Code = "CZK", Name = "Czech koruna", Symbol = "Kč", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 40, Code = "DJF", Name = "Djiboutian franc", Symbol = "Fdj", Format = "###,###,##0", DecimalPlaces = 0 },
            new Currency { CurrencyId = 41, Code = "DKK", Name = "Danish krone", Symbol = "Kr.", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 42, Code = "DOP", Name = "Dominican peso", Symbol = "$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 43, Code = "DZD", Name = "Algerian dinar", Symbol = "دج", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 44, Code = "EGP", Name = "Egyptian pound", Symbol = "ج.م", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 45, Code = "ERN", Name = "Eritrean nakfa", Symbol = "Nfk", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 46, Code = "ETB", Name = "Ethiopian birr", Symbol = "Nkf", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 47, Code = "EUR", Name = "Euro", Symbol = "€", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 48, Code = "FJD", Name = "Fijian dollar", Symbol = "FJ$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 49, Code = "FKP", Name = "Falkland Islands pound", Symbol = "£", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 50, Code = "GEL", Name = "Georgian lari", Symbol = "ლ", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 51, Code = "GHS", Name = "Ghanaian cedi", Symbol = "GH₵", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 52, Code = "GIP", Name = "Gibraltar pound", Symbol = "£", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 53, Code = "GMD", Name = "Gambian dalasi", Symbol = "D", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 54, Code = "GNF", Name = "Guinean franc", Symbol = "FG", Format = "###,###,##0", DecimalPlaces = 0 },
            new Currency { CurrencyId = 55, Code = "GTQ", Name = "Guatemalan quetzal", Symbol = "Q", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 56, Code = "GYD", Name = "Guyanese dollar", Symbol = "$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 57, Code = "HKD", Name = "Hong Kong dollar", Symbol = "$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 58, Code = "HNL", Name = "Honduran lempira", Symbol = "L", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 59, Code = "HTG", Name = "Haitian gourde", Symbol = "G", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 60, Code = "HUF", Name = "Hungarian forint", Symbol = "Ft", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 61, Code = "IDR", Name = "Indonesian rupiah", Symbol = "Rp", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 62, Code = "ILS", Name = "Israeli new shekel", Symbol = "₪", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 63, Code = "IQD", Name = "Iraqi dinar", Symbol = "د.ع", Format = "###,###,##0.000", DecimalPlaces = 3 },
            new Currency { CurrencyId = 64, Code = "IRR", Name = "Iranian rial", Symbol = "﷼", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 65, Code = "ISK", Name = "Icelandic króna", Symbol = "ko", Format = "###,###,##0", DecimalPlaces = 0 },
            new Currency { CurrencyId = 66, Code = "JMD", Name = "Jamaican dollar", Symbol = "J$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 67, Code = "JOD", Name = "Jordanian dinar", Symbol = "ا.د", Format = "###,###,##0.000", DecimalPlaces = 3 },
            new Currency { CurrencyId = 68, Code = "JPY", Name = "Japanese yen", Symbol = "¥", Format = "###,###,##0", DecimalPlaces = 0 },
            new Currency { CurrencyId = 69, Code = "KES", Name = "Kenyan shilling", Symbol = "KSh", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 70, Code = "KGS", Name = "Kyrgyzstani som", Symbol = "лв", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 71, Code = "KHR", Name = "Cambodian riel", Symbol = "KHR", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 72, Code = "KMF", Name = "Comorian franc", Symbol = "CF", Format = "###,###,##0", DecimalPlaces = 0 },
            new Currency { CurrencyId = 73, Code = "KPW", Name = "North Korean Won", Symbol = "₩", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 74, Code = "KRW", Name = "Won", Symbol = "₩", Format = "###,###,##0", DecimalPlaces = 0 },
            new Currency { CurrencyId = 75, Code = "KWD", Name = "Kuwaiti dinar", Symbol = "ك.د", Format = "###,###,##0.000", DecimalPlaces = 3 },
            new Currency { CurrencyId = 76, Code = "KYD", Name = "Cayman Islands dollar", Symbol = "$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 77, Code = "KZT", Name = "Kazakhstani tenge", Symbol = "лв", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 78, Code = "LAK", Name = "Lao kip", Symbol = "₭", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 79, Code = "LBP", Name = "Lebanese pound", Symbol = "£", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 80, Code = "LKR", Name = "Sri Lankan rupee", Symbol = "Rs", Format = "##,##,##,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 81, Code = "LRD", Name = "Liberian dollar", Symbol = "$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 82, Code = "LSL", Name = "Lesotho loti", Symbol = "L", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 83, Code = "LYD", Name = "Libyan dinar", Symbol = "د.ل", Format = "###,###,##0.000", DecimalPlaces = 3 },
            new Currency { CurrencyId = 84, Code = "MAD", Name = "Moroccan dirham", Symbol = "DH", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 85, Code = "MDL", Name = "Moldovan leu", Symbol = "L", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 86, Code = "MGA", Name = "Malagasy ariary", Symbol = "Ar", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 87, Code = "MKD", Name = "Denar", Symbol = "ден", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 88, Code = "MMK", Name = "Burmese kyat", Symbol = "K", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 89, Code = "MNT", Name = "Mongolian tögrög", Symbol = "₮", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 90, Code = "MOP", Name = "Macanese pataca", Symbol = "$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 91, Code = "MRU", Name = "Mauritanian ouguiya", Symbol = "UM", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 92, Code = "MUR", Name = "Mauritian rupee", Symbol = "₨", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 93, Code = "MVR", Name = "Maldivian rufiyaa", Symbol = "Rf", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 94, Code = "MWK", Name = "Malawian kwacha", Symbol = "MK", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 95, Code = "MXN", Name = "Mexican peso", Symbol = "$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 96, Code = "MYR", Name = "Malaysian ringgit", Symbol = "RM", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 97, Code = "MZN", Name = "Mozambican metical", Symbol = "MT", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 98, Code = "NAD", Name = "Namibian dollar", Symbol = "$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 99, Code = "NGN", Name = "Nigerian naira", Symbol = "₦", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 100, Code = "NIO", Name = "Nicaraguan córdoba", Symbol = "C$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 101, Code = "NOK", Name = "Norwegian krone", Symbol = "ko", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 102, Code = "NPR", Name = "Nepalese rupee", Symbol = "₨", Format = "##,##,##,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 103, Code = "NZD", Name = "New Zealand dollar", Symbol = "$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 104, Code = "OMR", Name = "Omani rial", Symbol = ".ع.ر", Format = "###,###,##0.000", DecimalPlaces = 3 },
            new Currency { CurrencyId = 105, Code = "PAB", Name = "Panamanian balboa", Symbol = "B/.", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 106, Code = "PEN", Name = "Peruvian sol", Symbol = "S/.", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 107, Code = "PGK", Name = "Papua New Guinean kina", Symbol = "K", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 108, Code = "PHP", Name = "Philippine peso", Symbol = "₱", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 109, Code = "PKR", Name = "Pakistani rupee", Symbol = "₨", Format = "##,##,##,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 110, Code = "PLN", Name = "Polish złoty", Symbol = "zł", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 111, Code = "PYG", Name = "Paraguayan guarani", Symbol = "₲", Format = "###,###,##0", DecimalPlaces = 0 },
            new Currency { CurrencyId = 112, Code = "QAR", Name = "Qatari riyal", Symbol = "ق.ر", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 113, Code = "RON", Name = "Romanian leu", Symbol = "lei", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 114, Code = "RSD", Name = "Serbian dinar", Symbol = "din", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 115, Code = "RUB", Name = "Russian ruble", Symbol = "₽", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 116, Code = "RWF", Name = "Rwandan franc", Symbol = "FRw", Format = "###,###,##0", DecimalPlaces = 0 },
            new Currency { CurrencyId = 117, Code = "SAR", Name = "Saudi riyal", Symbol = "﷼", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 118, Code = "SBD", Name = "Solomon Islands dollar", Symbol = "Si$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 119, Code = "SCR", Name = "Seychellois rupee", Symbol = "SRe", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 120, Code = "SDG", Name = "Sudanese pound", Symbol = ".س.ج", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 121, Code = "SEK", Name = "Swedish krona", Symbol = "ko", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 122, Code = "SHP", Name = "Saint Helena pound", Symbol = "£", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 123, Code = "SLL", Name = "Sierra Leonean leone", Symbol = "Le", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 124, Code = "SOS", Name = "Somali shilling", Symbol = "Sh.so.", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 125, Code = "SRD", Name = "Surinamese dollar", Symbol = "$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 126, Code = "SSP", Name = "South Sudanese pound", Symbol = "£", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 127, Code = "STN", Name = "Dobra", Symbol = "Db", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 128, Code = "SYP", Name = "Syrian pound", Symbol = "LS", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 129, Code = "SZL", Name = "Lilangeni", Symbol = "E", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 130, Code = "THB", Name = "Thai baht", Symbol = "฿", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 131, Code = "TJS", Name = "Tajikistani somoni", Symbol = "SM", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 132, Code = "TMT", Name = "Turkmenistan manat", Symbol = "T", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 133, Code = "TND", Name = "Tunisian dinar", Symbol = "ت.د", Format = "###,###,##0.000", DecimalPlaces = 3 },
            new Currency { CurrencyId = 134, Code = "TOP", Name = "Tongan paʻanga", Symbol = "$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 135, Code = "TRY", Name = "Turkish lira", Symbol = "₺", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 136, Code = "TTD", Name = "Trinidad and Tobago dollar", Symbol = "$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 137, Code = "TWD", Name = "New Taiwan dollar", Symbol = "$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 138, Code = "TZS", Name = "Tanzanian shilling", Symbol = "TSh", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 139, Code = "UAH", Name = "Ukrainian hryvnia", Symbol = "₴", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 140, Code = "UGX", Name = "Ugandan shilling", Symbol = "USh", Format = "###,###,##0", DecimalPlaces = 0 },
            new Currency { CurrencyId = 141, Code = "UYU", Name = "Uruguayan peso", Symbol = "$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 142, Code = "UZS", Name = "Uzbekistani soʻm", Symbol = "лв", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 143, Code = "VES", Name = "Bolívar", Symbol = "Bs", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 144, Code = "VND", Name = "Vietnamese đồng", Symbol = "₫", Format = "###,###,##0", DecimalPlaces = 0 },
            new Currency { CurrencyId = 145, Code = "VUV", Name = "Vanuatu vatu", Symbol = "VT", Format = "###,###,##0", DecimalPlaces = 0 },
            new Currency { CurrencyId = 146, Code = "WST", Name = "Samoan tālā", Symbol = "SAT", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 147, Code = "XAF", Name = "Central African CFA franc", Symbol = "FCFA", Format = "###,###,##0", DecimalPlaces = 0 },
            new Currency { CurrencyId = 148, Code = "XCD", Name = "Eastern Caribbean dollar", Symbol = "$", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 149, Code = "XOF", Name = "West African CFA franc", Symbol = "CFA", Format = "###,###,##0", DecimalPlaces = 0 },
            new Currency { CurrencyId = 150, Code = "XPF", Name = "CFP franc", Symbol = "₣", Format = "###,###,##0", DecimalPlaces = 0 },
            new Currency { CurrencyId = 151, Code = "YER", Name = "Yemeni rial", Symbol = "﷼", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 152, Code = "ZAR", Name = "South African rand", Symbol = "R", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 153, Code = "ZMW", Name = "Zambian kwacha", Symbol = "ZK", Format = "###,###,##0.00", DecimalPlaces = 2 },
            new Currency { CurrencyId = 154, Code = "ZWL", Name = "Zimbabwe Dollar", Symbol = "$", Format = "###,###,##0.00", DecimalPlaces = 2 },
        };
    }

    public static IReadOnlyList<Country> GetCountries()
    {
        return new List<Country>
        {
            new Country { CountryId = 1, CountryCode = "IN", CountryName = "India", CurrencyCode = "INR", PhoneCode = "+91" },
            new Country { CountryId = 2, CountryCode = "US", CountryName = "United States", CurrencyCode = "USD", PhoneCode = "+1" },
            new Country { CountryId = 3, CountryCode = "GB", CountryName = "United Kingdom", CurrencyCode = "GBP", PhoneCode = "+44" },
            new Country { CountryId = 4, CountryCode = "AE", CountryName = "United Arab Emirates", CurrencyCode = "AED", PhoneCode = "+971" },
            new Country { CountryId = 5, CountryCode = "SG", CountryName = "Singapore", CurrencyCode = "SGD", PhoneCode = "+65" },
            new Country { CountryId = 6, CountryCode = "AF", CountryName = "Afghanistan", CurrencyCode = "AFN", PhoneCode = "+93" },
            new Country { CountryId = 7, CountryCode = "AX", CountryName = "Aland Islands", CurrencyCode = "EUR", PhoneCode = "+358" },
            new Country { CountryId = 8, CountryCode = "AL", CountryName = "Albania", CurrencyCode = "ALL", PhoneCode = "+355" },
            new Country { CountryId = 9, CountryCode = "DZ", CountryName = "Algeria", CurrencyCode = "DZD", PhoneCode = "+213" },
            new Country { CountryId = 10, CountryCode = "AS", CountryName = "American Samoa", CurrencyCode = "USD", PhoneCode = "+1" },
            new Country { CountryId = 11, CountryCode = "AD", CountryName = "Andorra", CurrencyCode = "EUR", PhoneCode = "+376" },
            new Country { CountryId = 12, CountryCode = "AO", CountryName = "Angola", CurrencyCode = "AOA", PhoneCode = "+244" },
            new Country { CountryId = 13, CountryCode = "AI", CountryName = "Anguilla", CurrencyCode = "XCD", PhoneCode = "+1" },
            new Country { CountryId = 14, CountryCode = "AQ", CountryName = "Antarctica", CurrencyCode = "AAD", PhoneCode = "+672" },
            new Country { CountryId = 15, CountryCode = "AG", CountryName = "Antigua and Barbuda", CurrencyCode = "XCD", PhoneCode = "+1" },
            new Country { CountryId = 16, CountryCode = "AR", CountryName = "Argentina", CurrencyCode = "ARS", PhoneCode = "+54" },
            new Country { CountryId = 17, CountryCode = "AM", CountryName = "Armenia", CurrencyCode = "AMD", PhoneCode = "+374" },
            new Country { CountryId = 18, CountryCode = "AW", CountryName = "Aruba", CurrencyCode = "AWG", PhoneCode = "+297" },
            new Country { CountryId = 19, CountryCode = "AU", CountryName = "Australia", CurrencyCode = "AUD", PhoneCode = "+61" },
            new Country { CountryId = 20, CountryCode = "AT", CountryName = "Austria", CurrencyCode = "EUR", PhoneCode = "+43" },
            new Country { CountryId = 21, CountryCode = "AZ", CountryName = "Azerbaijan", CurrencyCode = "AZN", PhoneCode = "+994" },
            new Country { CountryId = 22, CountryCode = "BH", CountryName = "Bahrain", CurrencyCode = "BHD", PhoneCode = "+973" },
            new Country { CountryId = 23, CountryCode = "BD", CountryName = "Bangladesh", CurrencyCode = "BDT", PhoneCode = "+880" },
            new Country { CountryId = 24, CountryCode = "BB", CountryName = "Barbados", CurrencyCode = "BBD", PhoneCode = "+1" },
            new Country { CountryId = 25, CountryCode = "BY", CountryName = "Belarus", CurrencyCode = "BYN", PhoneCode = "+375" },
            new Country { CountryId = 26, CountryCode = "BE", CountryName = "Belgium", CurrencyCode = "EUR", PhoneCode = "+32" },
            new Country { CountryId = 27, CountryCode = "BZ", CountryName = "Belize", CurrencyCode = "BZD", PhoneCode = "+501" },
            new Country { CountryId = 28, CountryCode = "BJ", CountryName = "Benin", CurrencyCode = "XOF", PhoneCode = "+229" },
            new Country { CountryId = 29, CountryCode = "BM", CountryName = "Bermuda", CurrencyCode = "BMD", PhoneCode = "+1" },
            new Country { CountryId = 30, CountryCode = "BT", CountryName = "Bhutan", CurrencyCode = "BTN", PhoneCode = "+975" },
            new Country { CountryId = 31, CountryCode = "BO", CountryName = "Bolivia", CurrencyCode = "BOB", PhoneCode = "+591" },
            new Country { CountryId = 32, CountryCode = "BQ", CountryName = "Bonaire, Sint Eustatius and Saba", CurrencyCode = "USD", PhoneCode = "+599" },
            new Country { CountryId = 33, CountryCode = "BA", CountryName = "Bosnia and Herzegovina", CurrencyCode = "BAM", PhoneCode = "+387" },
            new Country { CountryId = 34, CountryCode = "BW", CountryName = "Botswana", CurrencyCode = "BWP", PhoneCode = "+267" },
            new Country { CountryId = 35, CountryCode = "BV", CountryName = "Bouvet Island", CurrencyCode = "NOK", PhoneCode = "+0055" },
            new Country { CountryId = 36, CountryCode = "BR", CountryName = "Brazil", CurrencyCode = "BRL", PhoneCode = "+55" },
            new Country { CountryId = 37, CountryCode = "IO", CountryName = "British Indian Ocean Territory", CurrencyCode = "USD", PhoneCode = "+246" },
            new Country { CountryId = 38, CountryCode = "BN", CountryName = "Brunei", CurrencyCode = "BND", PhoneCode = "+673" },
            new Country { CountryId = 39, CountryCode = "BG", CountryName = "Bulgaria", CurrencyCode = "EUR", PhoneCode = "+359" },
            new Country { CountryId = 40, CountryCode = "BF", CountryName = "Burkina Faso", CurrencyCode = "XOF", PhoneCode = "+226" },
            new Country { CountryId = 41, CountryCode = "BI", CountryName = "Burundi", CurrencyCode = "BIF", PhoneCode = "+257" },
            new Country { CountryId = 42, CountryCode = "KH", CountryName = "Cambodia", CurrencyCode = "KHR", PhoneCode = "+855" },
            new Country { CountryId = 43, CountryCode = "CM", CountryName = "Cameroon", CurrencyCode = "XAF", PhoneCode = "+237" },
            new Country { CountryId = 44, CountryCode = "CA", CountryName = "Canada", CurrencyCode = "CAD", PhoneCode = "+1" },
            new Country { CountryId = 45, CountryCode = "CV", CountryName = "Cape Verde", CurrencyCode = "CVE", PhoneCode = "+238" },
            new Country { CountryId = 46, CountryCode = "KY", CountryName = "Cayman Islands", CurrencyCode = "KYD", PhoneCode = "+1" },
            new Country { CountryId = 47, CountryCode = "CF", CountryName = "Central African Republic", CurrencyCode = "XAF", PhoneCode = "+236" },
            new Country { CountryId = 48, CountryCode = "TD", CountryName = "Chad", CurrencyCode = "XAF", PhoneCode = "+235" },
            new Country { CountryId = 49, CountryCode = "CL", CountryName = "Chile", CurrencyCode = "CLP", PhoneCode = "+56" },
            new Country { CountryId = 50, CountryCode = "CN", CountryName = "China", CurrencyCode = "CNY", PhoneCode = "+86" },
            new Country { CountryId = 51, CountryCode = "CX", CountryName = "Christmas Island", CurrencyCode = "AUD", PhoneCode = "+61" },
            new Country { CountryId = 52, CountryCode = "CC", CountryName = "Cocos (Keeling) Islands", CurrencyCode = "AUD", PhoneCode = "+61" },
            new Country { CountryId = 53, CountryCode = "CO", CountryName = "Colombia", CurrencyCode = "COP", PhoneCode = "+57" },
            new Country { CountryId = 54, CountryCode = "KM", CountryName = "Comoros", CurrencyCode = "KMF", PhoneCode = "+269" },
            new Country { CountryId = 55, CountryCode = "CG", CountryName = "Congo", CurrencyCode = "CDF", PhoneCode = "+242" },
            new Country { CountryId = 56, CountryCode = "CK", CountryName = "Cook Islands", CurrencyCode = "NZD", PhoneCode = "+682" },
            new Country { CountryId = 57, CountryCode = "CR", CountryName = "Costa Rica", CurrencyCode = "CRC", PhoneCode = "+506" },
            new Country { CountryId = 58, CountryCode = "HR", CountryName = "Croatia", CurrencyCode = "EUR", PhoneCode = "+385" },
            new Country { CountryId = 59, CountryCode = "CU", CountryName = "Cuba", CurrencyCode = "CUP", PhoneCode = "+53" },
            new Country { CountryId = 60, CountryCode = "CW", CountryName = "Curaçao", CurrencyCode = "ANG", PhoneCode = "+599" },
            new Country { CountryId = 61, CountryCode = "CY", CountryName = "Cyprus", CurrencyCode = "EUR", PhoneCode = "+357" },
            new Country { CountryId = 62, CountryCode = "CZ", CountryName = "Czech Republic", CurrencyCode = "CZK", PhoneCode = "+420" },
            new Country { CountryId = 63, CountryCode = "CD", CountryName = "Democratic Republic of the Congo", CurrencyCode = "CDF", PhoneCode = "+243" },
            new Country { CountryId = 64, CountryCode = "DK", CountryName = "Denmark", CurrencyCode = "DKK", PhoneCode = "+45" },
            new Country { CountryId = 65, CountryCode = "DJ", CountryName = "Djibouti", CurrencyCode = "DJF", PhoneCode = "+253" },
            new Country { CountryId = 66, CountryCode = "DM", CountryName = "Dominica", CurrencyCode = "XCD", PhoneCode = "+1" },
            new Country { CountryId = 67, CountryCode = "DO", CountryName = "Dominican Republic", CurrencyCode = "DOP", PhoneCode = "+1" },
            new Country { CountryId = 68, CountryCode = "EC", CountryName = "Ecuador", CurrencyCode = "USD", PhoneCode = "+593" },
            new Country { CountryId = 69, CountryCode = "EG", CountryName = "Egypt", CurrencyCode = "EGP", PhoneCode = "+20" },
            new Country { CountryId = 70, CountryCode = "SV", CountryName = "El Salvador", CurrencyCode = "USD", PhoneCode = "+503" },
            new Country { CountryId = 71, CountryCode = "GQ", CountryName = "Equatorial Guinea", CurrencyCode = "XAF", PhoneCode = "+240" },
            new Country { CountryId = 72, CountryCode = "ER", CountryName = "Eritrea", CurrencyCode = "ERN", PhoneCode = "+291" },
            new Country { CountryId = 73, CountryCode = "EE", CountryName = "Estonia", CurrencyCode = "EUR", PhoneCode = "+372" },
            new Country { CountryId = 74, CountryCode = "SZ", CountryName = "Eswatini", CurrencyCode = "SZL", PhoneCode = "+268" },
            new Country { CountryId = 75, CountryCode = "ET", CountryName = "Ethiopia", CurrencyCode = "ETB", PhoneCode = "+251" },
            new Country { CountryId = 76, CountryCode = "FK", CountryName = "Falkland Islands", CurrencyCode = "FKP", PhoneCode = "+500" },
            new Country { CountryId = 77, CountryCode = "FO", CountryName = "Faroe Islands", CurrencyCode = "DKK", PhoneCode = "+298" },
            new Country { CountryId = 78, CountryCode = "FJ", CountryName = "Fiji Islands", CurrencyCode = "FJD", PhoneCode = "+679" },
            new Country { CountryId = 79, CountryCode = "FI", CountryName = "Finland", CurrencyCode = "EUR", PhoneCode = "+358" },
            new Country { CountryId = 80, CountryCode = "FR", CountryName = "France", CurrencyCode = "EUR", PhoneCode = "+33" },
            new Country { CountryId = 81, CountryCode = "GF", CountryName = "French Guiana", CurrencyCode = "EUR", PhoneCode = "+594" },
            new Country { CountryId = 82, CountryCode = "PF", CountryName = "French Polynesia", CurrencyCode = "XPF", PhoneCode = "+689" },
            new Country { CountryId = 83, CountryCode = "TF", CountryName = "French Southern Territories", CurrencyCode = "EUR", PhoneCode = "+262" },
            new Country { CountryId = 84, CountryCode = "GA", CountryName = "Gabon", CurrencyCode = "XAF", PhoneCode = "+241" },
            new Country { CountryId = 85, CountryCode = "GE", CountryName = "Georgia", CurrencyCode = "GEL", PhoneCode = "+995" },
            new Country { CountryId = 86, CountryCode = "DE", CountryName = "Germany", CurrencyCode = "EUR", PhoneCode = "+49" },
            new Country { CountryId = 87, CountryCode = "GH", CountryName = "Ghana", CurrencyCode = "GHS", PhoneCode = "+233" },
            new Country { CountryId = 88, CountryCode = "GI", CountryName = "Gibraltar", CurrencyCode = "GIP", PhoneCode = "+350" },
            new Country { CountryId = 89, CountryCode = "GR", CountryName = "Greece", CurrencyCode = "EUR", PhoneCode = "+30" },
            new Country { CountryId = 90, CountryCode = "GL", CountryName = "Greenland", CurrencyCode = "DKK", PhoneCode = "+299" },
            new Country { CountryId = 91, CountryCode = "GD", CountryName = "Grenada", CurrencyCode = "XCD", PhoneCode = "+1" },
            new Country { CountryId = 92, CountryCode = "GP", CountryName = "Guadeloupe", CurrencyCode = "EUR", PhoneCode = "+590" },
            new Country { CountryId = 93, CountryCode = "GU", CountryName = "Guam", CurrencyCode = "USD", PhoneCode = "+1" },
            new Country { CountryId = 94, CountryCode = "GT", CountryName = "Guatemala", CurrencyCode = "GTQ", PhoneCode = "+502" },
            new Country { CountryId = 95, CountryCode = "GG", CountryName = "Guernsey", CurrencyCode = "GBP", PhoneCode = "+44" },
            new Country { CountryId = 96, CountryCode = "GN", CountryName = "Guinea", CurrencyCode = "GNF", PhoneCode = "+224" },
            new Country { CountryId = 97, CountryCode = "GW", CountryName = "Guinea-Bissau", CurrencyCode = "XOF", PhoneCode = "+245" },
            new Country { CountryId = 98, CountryCode = "GY", CountryName = "Guyana", CurrencyCode = "GYD", PhoneCode = "+592" },
            new Country { CountryId = 99, CountryCode = "HT", CountryName = "Haiti", CurrencyCode = "HTG", PhoneCode = "+509" },
            new Country { CountryId = 100, CountryCode = "HM", CountryName = "Heard Island and McDonald Islands", CurrencyCode = "AUD", PhoneCode = "+672" },
            new Country { CountryId = 101, CountryCode = "HN", CountryName = "Honduras", CurrencyCode = "HNL", PhoneCode = "+504" },
            new Country { CountryId = 102, CountryCode = "HK", CountryName = "Hong Kong S.A.R.", CurrencyCode = "HKD", PhoneCode = "+852" },
            new Country { CountryId = 103, CountryCode = "HU", CountryName = "Hungary", CurrencyCode = "HUF", PhoneCode = "+36" },
            new Country { CountryId = 104, CountryCode = "IS", CountryName = "Iceland", CurrencyCode = "ISK", PhoneCode = "+354" },
            new Country { CountryId = 105, CountryCode = "ID", CountryName = "Indonesia", CurrencyCode = "IDR", PhoneCode = "+62" },
            new Country { CountryId = 106, CountryCode = "IR", CountryName = "Iran", CurrencyCode = "IRR", PhoneCode = "+98" },
            new Country { CountryId = 107, CountryCode = "IQ", CountryName = "Iraq", CurrencyCode = "IQD", PhoneCode = "+964" },
            new Country { CountryId = 108, CountryCode = "IE", CountryName = "Ireland", CurrencyCode = "EUR", PhoneCode = "+353" },
            new Country { CountryId = 109, CountryCode = "IL", CountryName = "Israel", CurrencyCode = "ILS", PhoneCode = "+972" },
            new Country { CountryId = 110, CountryCode = "IT", CountryName = "Italy", CurrencyCode = "EUR", PhoneCode = "+39" },
            new Country { CountryId = 111, CountryCode = "CI", CountryName = "Ivory Coast", CurrencyCode = "XOF", PhoneCode = "+225" },
            new Country { CountryId = 112, CountryCode = "JM", CountryName = "Jamaica", CurrencyCode = "JMD", PhoneCode = "+1" },
            new Country { CountryId = 113, CountryCode = "JP", CountryName = "Japan", CurrencyCode = "JPY", PhoneCode = "+81" },
            new Country { CountryId = 114, CountryCode = "JE", CountryName = "Jersey", CurrencyCode = "GBP", PhoneCode = "+44" },
            new Country { CountryId = 115, CountryCode = "JO", CountryName = "Jordan", CurrencyCode = "JOD", PhoneCode = "+962" },
            new Country { CountryId = 116, CountryCode = "KZ", CountryName = "Kazakhstan", CurrencyCode = "KZT", PhoneCode = "+7" },
            new Country { CountryId = 117, CountryCode = "KE", CountryName = "Kenya", CurrencyCode = "KES", PhoneCode = "+254" },
            new Country { CountryId = 118, CountryCode = "KI", CountryName = "Kiribati", CurrencyCode = "AUD", PhoneCode = "+686" },
            new Country { CountryId = 119, CountryCode = "XK", CountryName = "Kosovo", CurrencyCode = "EUR", PhoneCode = "+383" },
            new Country { CountryId = 120, CountryCode = "KW", CountryName = "Kuwait", CurrencyCode = "KWD", PhoneCode = "+965" },
            new Country { CountryId = 121, CountryCode = "KG", CountryName = "Kyrgyzstan", CurrencyCode = "KGS", PhoneCode = "+996" },
            new Country { CountryId = 122, CountryCode = "LA", CountryName = "Laos", CurrencyCode = "LAK", PhoneCode = "+856" },
            new Country { CountryId = 123, CountryCode = "LV", CountryName = "Latvia", CurrencyCode = "EUR", PhoneCode = "+371" },
            new Country { CountryId = 124, CountryCode = "LB", CountryName = "Lebanon", CurrencyCode = "LBP", PhoneCode = "+961" },
            new Country { CountryId = 125, CountryCode = "LS", CountryName = "Lesotho", CurrencyCode = "LSL", PhoneCode = "+266" },
            new Country { CountryId = 126, CountryCode = "LR", CountryName = "Liberia", CurrencyCode = "LRD", PhoneCode = "+231" },
            new Country { CountryId = 127, CountryCode = "LY", CountryName = "Libya", CurrencyCode = "LYD", PhoneCode = "+218" },
            new Country { CountryId = 128, CountryCode = "LI", CountryName = "Liechtenstein", CurrencyCode = "CHF", PhoneCode = "+423" },
            new Country { CountryId = 129, CountryCode = "LT", CountryName = "Lithuania", CurrencyCode = "EUR", PhoneCode = "+370" },
            new Country { CountryId = 130, CountryCode = "LU", CountryName = "Luxembourg", CurrencyCode = "EUR", PhoneCode = "+352" },
            new Country { CountryId = 131, CountryCode = "MO", CountryName = "Macau S.A.R.", CurrencyCode = "MOP", PhoneCode = "+853" },
            new Country { CountryId = 132, CountryCode = "MG", CountryName = "Madagascar", CurrencyCode = "MGA", PhoneCode = "+261" },
            new Country { CountryId = 133, CountryCode = "MW", CountryName = "Malawi", CurrencyCode = "MWK", PhoneCode = "+265" },
            new Country { CountryId = 134, CountryCode = "MY", CountryName = "Malaysia", CurrencyCode = "MYR", PhoneCode = "+60" },
            new Country { CountryId = 135, CountryCode = "MV", CountryName = "Maldives", CurrencyCode = "MVR", PhoneCode = "+960" },
            new Country { CountryId = 136, CountryCode = "ML", CountryName = "Mali", CurrencyCode = "XOF", PhoneCode = "+223" },
            new Country { CountryId = 137, CountryCode = "MT", CountryName = "Malta", CurrencyCode = "EUR", PhoneCode = "+356" },
            new Country { CountryId = 138, CountryCode = "IM", CountryName = "Man (Isle of)", CurrencyCode = "GBP", PhoneCode = "+44" },
            new Country { CountryId = 139, CountryCode = "MH", CountryName = "Marshall Islands", CurrencyCode = "USD", PhoneCode = "+692" },
            new Country { CountryId = 140, CountryCode = "MQ", CountryName = "Martinique", CurrencyCode = "EUR", PhoneCode = "+596" },
            new Country { CountryId = 141, CountryCode = "MR", CountryName = "Mauritania", CurrencyCode = "MRU", PhoneCode = "+222" },
            new Country { CountryId = 142, CountryCode = "MU", CountryName = "Mauritius", CurrencyCode = "MUR", PhoneCode = "+230" },
            new Country { CountryId = 143, CountryCode = "YT", CountryName = "Mayotte", CurrencyCode = "EUR", PhoneCode = "+262" },
            new Country { CountryId = 144, CountryCode = "MX", CountryName = "Mexico", CurrencyCode = "MXN", PhoneCode = "+52" },
            new Country { CountryId = 145, CountryCode = "FM", CountryName = "Micronesia", CurrencyCode = "USD", PhoneCode = "+691" },
            new Country { CountryId = 146, CountryCode = "MD", CountryName = "Moldova", CurrencyCode = "MDL", PhoneCode = "+373" },
            new Country { CountryId = 147, CountryCode = "MC", CountryName = "Monaco", CurrencyCode = "EUR", PhoneCode = "+377" },
            new Country { CountryId = 148, CountryCode = "MN", CountryName = "Mongolia", CurrencyCode = "MNT", PhoneCode = "+976" },
            new Country { CountryId = 149, CountryCode = "ME", CountryName = "Montenegro", CurrencyCode = "EUR", PhoneCode = "+382" },
            new Country { CountryId = 150, CountryCode = "MS", CountryName = "Montserrat", CurrencyCode = "XCD", PhoneCode = "+1" },
            new Country { CountryId = 151, CountryCode = "MA", CountryName = "Morocco", CurrencyCode = "MAD", PhoneCode = "+212" },
            new Country { CountryId = 152, CountryCode = "MZ", CountryName = "Mozambique", CurrencyCode = "MZN", PhoneCode = "+258" },
            new Country { CountryId = 153, CountryCode = "MM", CountryName = "Myanmar", CurrencyCode = "MMK", PhoneCode = "+95" },
            new Country { CountryId = 154, CountryCode = "NA", CountryName = "Namibia", CurrencyCode = "NAD", PhoneCode = "+264" },
            new Country { CountryId = 155, CountryCode = "NR", CountryName = "Nauru", CurrencyCode = "AUD", PhoneCode = "+674" },
            new Country { CountryId = 156, CountryCode = "NP", CountryName = "Nepal", CurrencyCode = "NPR", PhoneCode = "+977" },
            new Country { CountryId = 157, CountryCode = "NL", CountryName = "Netherlands", CurrencyCode = "EUR", PhoneCode = "+31" },
            new Country { CountryId = 158, CountryCode = "NC", CountryName = "New Caledonia", CurrencyCode = "XPF", PhoneCode = "+687" },
            new Country { CountryId = 159, CountryCode = "NZ", CountryName = "New Zealand", CurrencyCode = "NZD", PhoneCode = "+64" },
            new Country { CountryId = 160, CountryCode = "NI", CountryName = "Nicaragua", CurrencyCode = "NIO", PhoneCode = "+505" },
            new Country { CountryId = 161, CountryCode = "NE", CountryName = "Niger", CurrencyCode = "XOF", PhoneCode = "+227" },
            new Country { CountryId = 162, CountryCode = "NG", CountryName = "Nigeria", CurrencyCode = "NGN", PhoneCode = "+234" },
            new Country { CountryId = 163, CountryCode = "NU", CountryName = "Niue", CurrencyCode = "NZD", PhoneCode = "+683" },
            new Country { CountryId = 164, CountryCode = "NF", CountryName = "Norfolk Island", CurrencyCode = "AUD", PhoneCode = "+672" },
            new Country { CountryId = 165, CountryCode = "KP", CountryName = "North Korea", CurrencyCode = "KPW", PhoneCode = "+850" },
            new Country { CountryId = 166, CountryCode = "MK", CountryName = "North Macedonia", CurrencyCode = "MKD", PhoneCode = "+389" },
            new Country { CountryId = 167, CountryCode = "MP", CountryName = "Northern Mariana Islands", CurrencyCode = "USD", PhoneCode = "+1" },
            new Country { CountryId = 168, CountryCode = "NO", CountryName = "Norway", CurrencyCode = "NOK", PhoneCode = "+47" },
            new Country { CountryId = 169, CountryCode = "OM", CountryName = "Oman", CurrencyCode = "OMR", PhoneCode = "+968" },
            new Country { CountryId = 170, CountryCode = "PK", CountryName = "Pakistan", CurrencyCode = "PKR", PhoneCode = "+92" },
            new Country { CountryId = 171, CountryCode = "PW", CountryName = "Palau", CurrencyCode = "USD", PhoneCode = "+680" },
            new Country { CountryId = 172, CountryCode = "PS", CountryName = "Palestinian Territory Occupied", CurrencyCode = "ILS", PhoneCode = "+970" },
            new Country { CountryId = 173, CountryCode = "PA", CountryName = "Panama", CurrencyCode = "PAB", PhoneCode = "+507" },
            new Country { CountryId = 174, CountryCode = "PG", CountryName = "Papua New Guinea", CurrencyCode = "PGK", PhoneCode = "+675" },
            new Country { CountryId = 175, CountryCode = "PY", CountryName = "Paraguay", CurrencyCode = "PYG", PhoneCode = "+595" },
            new Country { CountryId = 176, CountryCode = "PE", CountryName = "Peru", CurrencyCode = "PEN", PhoneCode = "+51" },
            new Country { CountryId = 177, CountryCode = "PH", CountryName = "Philippines", CurrencyCode = "PHP", PhoneCode = "+63" },
            new Country { CountryId = 178, CountryCode = "PN", CountryName = "Pitcairn Island", CurrencyCode = "NZD", PhoneCode = "+870" },
            new Country { CountryId = 179, CountryCode = "PL", CountryName = "Poland", CurrencyCode = "PLN", PhoneCode = "+48" },
            new Country { CountryId = 180, CountryCode = "PT", CountryName = "Portugal", CurrencyCode = "EUR", PhoneCode = "+351" },
            new Country { CountryId = 181, CountryCode = "PR", CountryName = "Puerto Rico", CurrencyCode = "USD", PhoneCode = "+1" },
            new Country { CountryId = 182, CountryCode = "QA", CountryName = "Qatar", CurrencyCode = "QAR", PhoneCode = "+974" },
            new Country { CountryId = 183, CountryCode = "RE", CountryName = "Reunion", CurrencyCode = "EUR", PhoneCode = "+262" },
            new Country { CountryId = 184, CountryCode = "RO", CountryName = "Romania", CurrencyCode = "RON", PhoneCode = "+40" },
            new Country { CountryId = 185, CountryCode = "RU", CountryName = "Russia", CurrencyCode = "RUB", PhoneCode = "+7" },
            new Country { CountryId = 186, CountryCode = "RW", CountryName = "Rwanda", CurrencyCode = "RWF", PhoneCode = "+250" },
            new Country { CountryId = 187, CountryCode = "SH", CountryName = "Saint Helena", CurrencyCode = "SHP", PhoneCode = "+290" },
            new Country { CountryId = 188, CountryCode = "KN", CountryName = "Saint Kitts and Nevis", CurrencyCode = "XCD", PhoneCode = "+1" },
            new Country { CountryId = 189, CountryCode = "LC", CountryName = "Saint Lucia", CurrencyCode = "XCD", PhoneCode = "+1" },
            new Country { CountryId = 190, CountryCode = "PM", CountryName = "Saint Pierre and Miquelon", CurrencyCode = "EUR", PhoneCode = "+508" },
            new Country { CountryId = 191, CountryCode = "VC", CountryName = "Saint Vincent and the Grenadines", CurrencyCode = "XCD", PhoneCode = "+1" },
            new Country { CountryId = 192, CountryCode = "BL", CountryName = "Saint-Barthelemy", CurrencyCode = "EUR", PhoneCode = "+590" },
            new Country { CountryId = 193, CountryCode = "MF", CountryName = "Saint-Martin (French part)", CurrencyCode = "EUR", PhoneCode = "+590" },
            new Country { CountryId = 194, CountryCode = "WS", CountryName = "Samoa", CurrencyCode = "WST", PhoneCode = "+685" },
            new Country { CountryId = 195, CountryCode = "SM", CountryName = "San Marino", CurrencyCode = "EUR", PhoneCode = "+378" },
            new Country { CountryId = 196, CountryCode = "ST", CountryName = "Sao Tome and Principe", CurrencyCode = "STN", PhoneCode = "+239" },
            new Country { CountryId = 197, CountryCode = "SA", CountryName = "Saudi Arabia", CurrencyCode = "SAR", PhoneCode = "+966" },
            new Country { CountryId = 198, CountryCode = "SN", CountryName = "Senegal", CurrencyCode = "XOF", PhoneCode = "+221" },
            new Country { CountryId = 199, CountryCode = "RS", CountryName = "Serbia", CurrencyCode = "RSD", PhoneCode = "+381" },
            new Country { CountryId = 200, CountryCode = "SC", CountryName = "Seychelles", CurrencyCode = "SCR", PhoneCode = "+248" },
            new Country { CountryId = 201, CountryCode = "SL", CountryName = "Sierra Leone", CurrencyCode = "SLL", PhoneCode = "+232" },
            new Country { CountryId = 202, CountryCode = "SX", CountryName = "Sint Maarten (Dutch part)", CurrencyCode = "ANG", PhoneCode = "+1721" },
            new Country { CountryId = 203, CountryCode = "SK", CountryName = "Slovakia", CurrencyCode = "EUR", PhoneCode = "+421" },
            new Country { CountryId = 204, CountryCode = "SI", CountryName = "Slovenia", CurrencyCode = "EUR", PhoneCode = "+386" },
            new Country { CountryId = 205, CountryCode = "SB", CountryName = "Solomon Islands", CurrencyCode = "SBD", PhoneCode = "+677" },
            new Country { CountryId = 206, CountryCode = "SO", CountryName = "Somalia", CurrencyCode = "SOS", PhoneCode = "+252" },
            new Country { CountryId = 207, CountryCode = "ZA", CountryName = "South Africa", CurrencyCode = "ZAR", PhoneCode = "+27" },
            new Country { CountryId = 208, CountryCode = "GS", CountryName = "South Georgia", CurrencyCode = "GBP", PhoneCode = "+500" },
            new Country { CountryId = 209, CountryCode = "KR", CountryName = "South Korea", CurrencyCode = "KRW", PhoneCode = "+82" },
            new Country { CountryId = 210, CountryCode = "SS", CountryName = "South Sudan", CurrencyCode = "SSP", PhoneCode = "+211" },
            new Country { CountryId = 211, CountryCode = "ES", CountryName = "Spain", CurrencyCode = "EUR", PhoneCode = "+34" },
            new Country { CountryId = 212, CountryCode = "LK", CountryName = "Sri Lanka", CurrencyCode = "LKR", PhoneCode = "+94" },
            new Country { CountryId = 213, CountryCode = "SD", CountryName = "Sudan", CurrencyCode = "SDG", PhoneCode = "+249" },
            new Country { CountryId = 214, CountryCode = "SR", CountryName = "Suriname", CurrencyCode = "SRD", PhoneCode = "+597" },
            new Country { CountryId = 215, CountryCode = "SJ", CountryName = "Svalbard and Jan Mayen Islands", CurrencyCode = "NOK", PhoneCode = "+47" },
            new Country { CountryId = 216, CountryCode = "SE", CountryName = "Sweden", CurrencyCode = "SEK", PhoneCode = "+46" },
            new Country { CountryId = 217, CountryCode = "CH", CountryName = "Switzerland", CurrencyCode = "CHF", PhoneCode = "+41" },
            new Country { CountryId = 218, CountryCode = "SY", CountryName = "Syria", CurrencyCode = "SYP", PhoneCode = "+963" },
            new Country { CountryId = 219, CountryCode = "TW", CountryName = "Taiwan", CurrencyCode = "TWD", PhoneCode = "+886" },
            new Country { CountryId = 220, CountryCode = "TJ", CountryName = "Tajikistan", CurrencyCode = "TJS", PhoneCode = "+992" },
            new Country { CountryId = 221, CountryCode = "TZ", CountryName = "Tanzania", CurrencyCode = "TZS", PhoneCode = "+255" },
            new Country { CountryId = 222, CountryCode = "TH", CountryName = "Thailand", CurrencyCode = "THB", PhoneCode = "+66" },
            new Country { CountryId = 223, CountryCode = "BS", CountryName = "The Bahamas", CurrencyCode = "BSD", PhoneCode = "+1" },
            new Country { CountryId = 224, CountryCode = "GM", CountryName = "The Gambia", CurrencyCode = "GMD", PhoneCode = "+220" },
            new Country { CountryId = 225, CountryCode = "TL", CountryName = "Timor-Leste", CurrencyCode = "USD", PhoneCode = "+670" },
            new Country { CountryId = 226, CountryCode = "TG", CountryName = "Togo", CurrencyCode = "XOF", PhoneCode = "+228" },
            new Country { CountryId = 227, CountryCode = "TK", CountryName = "Tokelau", CurrencyCode = "NZD", PhoneCode = "+690" },
            new Country { CountryId = 228, CountryCode = "TO", CountryName = "Tonga", CurrencyCode = "TOP", PhoneCode = "+676" },
            new Country { CountryId = 229, CountryCode = "TT", CountryName = "Trinidad and Tobago", CurrencyCode = "TTD", PhoneCode = "+1" },
            new Country { CountryId = 230, CountryCode = "TN", CountryName = "Tunisia", CurrencyCode = "TND", PhoneCode = "+216" },
            new Country { CountryId = 231, CountryCode = "TR", CountryName = "Turkey", CurrencyCode = "TRY", PhoneCode = "+90" },
            new Country { CountryId = 232, CountryCode = "TM", CountryName = "Turkmenistan", CurrencyCode = "TMT", PhoneCode = "+993" },
            new Country { CountryId = 233, CountryCode = "TC", CountryName = "Turks and Caicos Islands", CurrencyCode = "USD", PhoneCode = "+1" },
            new Country { CountryId = 234, CountryCode = "TV", CountryName = "Tuvalu", CurrencyCode = "AUD", PhoneCode = "+688" },
            new Country { CountryId = 235, CountryCode = "UG", CountryName = "Uganda", CurrencyCode = "UGX", PhoneCode = "+256" },
            new Country { CountryId = 236, CountryCode = "UA", CountryName = "Ukraine", CurrencyCode = "UAH", PhoneCode = "+380" },
            new Country { CountryId = 237, CountryCode = "UM", CountryName = "United States Minor Outlying Islands", CurrencyCode = "USD", PhoneCode = "+1" },
            new Country { CountryId = 238, CountryCode = "UY", CountryName = "Uruguay", CurrencyCode = "UYU", PhoneCode = "+598" },
            new Country { CountryId = 239, CountryCode = "UZ", CountryName = "Uzbekistan", CurrencyCode = "UZS", PhoneCode = "+998" },
            new Country { CountryId = 240, CountryCode = "VU", CountryName = "Vanuatu", CurrencyCode = "VUV", PhoneCode = "+678" },
            new Country { CountryId = 241, CountryCode = "VA", CountryName = "Vatican City State (Holy See)", CurrencyCode = "EUR", PhoneCode = "+379" },
            new Country { CountryId = 242, CountryCode = "VE", CountryName = "Venezuela", CurrencyCode = "VES", PhoneCode = "+58" },
            new Country { CountryId = 243, CountryCode = "VN", CountryName = "Vietnam", CurrencyCode = "VND", PhoneCode = "+84" },
            new Country { CountryId = 244, CountryCode = "VG", CountryName = "Virgin Islands (British)", CurrencyCode = "USD", PhoneCode = "+1" },
            new Country { CountryId = 245, CountryCode = "VI", CountryName = "Virgin Islands (US)", CurrencyCode = "USD", PhoneCode = "+1" },
            new Country { CountryId = 246, CountryCode = "WF", CountryName = "Wallis and Futuna Islands", CurrencyCode = "XPF", PhoneCode = "+681" },
            new Country { CountryId = 247, CountryCode = "EH", CountryName = "Western Sahara", CurrencyCode = "MAD", PhoneCode = "+212" },
            new Country { CountryId = 248, CountryCode = "YE", CountryName = "Yemen", CurrencyCode = "YER", PhoneCode = "+967" },
            new Country { CountryId = 249, CountryCode = "ZM", CountryName = "Zambia", CurrencyCode = "ZMW", PhoneCode = "+260" },
            new Country { CountryId = 250, CountryCode = "ZW", CountryName = "Zimbabwe", CurrencyCode = "ZWL", PhoneCode = "+263" },
        };
    }
}
