/**
 * TypeScript Design Token Constants and Definitions for Bill-Book
 */

export const TOKENS = {
  colors: {
    bg: '#f3f2f2',
    surface: '#eae9e9',
    text: '#201f1d',
    ink: '#2f353f',
    accent: '#f06311',
    accent2: '#ac803e',
    divider: 'color-mix(in srgb, #201f1d 16%, transparent)',
    border: 'color-mix(in srgb, #201f1d 16%, transparent)',
    neutral: {
      100: '#f8f4f4',
      200: '#eae7e7',
      300: '#d7d3d3',
      400: '#bab6b6',
      500: '#9b9797',
      600: '#7d7979',
      700: '#605d5d',
      800: '#444141',
      900: '#2d2b2b',
    },
    accentRamp: {
      100: '#fdefe4',
      200: '#ffe3bf',
      300: '#facb8d',
      400: '#f7853f',
      500: '#f06311',
      600: '#c94d08',
      700: '#a03d05',
      800: '#7a2f04',
      900: '#3a270d',
    },
    accent2Ramp: {
      100: '#fff3e4',
      200: '#ffe3be',
      300: '#f5cd96',
      400: '#dbaf70',
      500: '#bc8f4e',
      600: '#9b7232',
      700: '#79561f',
      800: '#573d14',
      900: '#382810',
    },
    alerts: {
      danger: '#a2332a',
      dangerBg: '#fbe4e0',
      warning: '#8a5b00',
      warningBg: '#fdf0d5',
      success: '#187a4b',
      successBg: '#e2f3e9',
    },
  },
  typography: {
    fontHeading: '"Cormorant Garamond", system-ui, sans-serif',
    fontHeadingWeight: 600,
    fontBody: '"Lora", system-ui, sans-serif',
    fontMono: 'Consolas, "Courier New", monospace',
  },
  spacing: {
    space1: '3px',
    space2: '7px',
    space3: '10px',
    space4: '13px',
    space6: '18px',
    space8: '24px',
    classical: {
      space1: '4.6px',
      space2: '9.2px',
      space3: '13.8px',
      space4: '18.4px',
      space6: '27.6px',
      space8: '36.8px',
    },
  },
  radii: {
    sm: '2px',
    md: '4px',
    lg: '7px',
    tag: '3px',
    pill: '999px',
    full: '999px',
  },
  shadows: {
    sm: '0 1px 2px color-mix(in srgb, #2d2b2b 14%, transparent)',
    md: '0 3px 10px color-mix(in srgb, #2d2b2b 16%, transparent)',
    lg: '0 12px 32px color-mix(in srgb, #2d2b2b 22%, transparent)',
    header: '0 8px 20px -10px rgba(32, 31, 29, 0.45), 0 3px 10px color-mix(in srgb, #2d2b2b 16%, transparent)',
    railActive: 'inset 4px 0 0 var(--color-accent), inset 13px 0 12px -10px rgba(32, 31, 29, 0.55)',
    tableHead: 'inset 0 -1px 0 color-mix(in srgb, var(--color-accent) 55%, transparent)',
  },
  zIndex: {
    topbar: 6,
    rail: 5,
    breadcrumbs: 4,
    tableHead: 3,
    content: 1,
    dropdown: 20,
    modal: 30,
    toast: 50,
  },
} as const;

export type DesignTokens = typeof TOKENS;

/**
 * Design Token Names (CSS Custom Properties)
 */
export const CSS_VARS = {
  color: {
    bg: 'var(--color-bg)',
    surface: 'var(--color-surface)',
    text: 'var(--color-text)',
    divider: 'var(--color-divider)',
    border: 'var(--color-border)',
    ink: 'var(--color-ink)',
    accent: 'var(--color-accent)',
    accent100: 'var(--color-accent-100)',
    accent200: 'var(--color-accent-200)',
    accent300: 'var(--color-accent-300)',
    accent400: 'var(--color-accent-400)',
    accent500: 'var(--color-accent-500)',
    accent600: 'var(--color-accent-600)',
    accent700: 'var(--color-accent-700)',
    accent800: 'var(--color-accent-800)',
    accent900: 'var(--color-accent-900)',
    accent2: 'var(--color-accent-2)',
    accent2_100: 'var(--color-accent-2-100)',
    accent2_200: 'var(--color-accent-2-200)',
    accent2_300: 'var(--color-accent-2-300)',
    accent2_400: 'var(--color-accent-2-400)',
    accent2_500: 'var(--color-accent-2-500)',
    accent2_600: 'var(--color-accent-2-600)',
    accent2_700: 'var(--color-accent-2-700)',
    accent2_800: 'var(--color-accent-2-800)',
    accent2_900: 'var(--color-accent-2-900)',
    neutral100: 'var(--color-neutral-100)',
    neutral200: 'var(--color-neutral-200)',
    neutral300: 'var(--color-neutral-300)',
    neutral400: 'var(--color-neutral-400)',
    neutral500: 'var(--color-neutral-500)',
    neutral600: 'var(--color-neutral-600)',
    neutral700: 'var(--color-neutral-700)',
    neutral800: 'var(--color-neutral-800)',
    neutral900: 'var(--color-neutral-900)',
    danger: 'var(--color-danger)',
    dangerBg: 'var(--color-danger-bg)',
    warning: 'var(--color-warning)',
    warningBg: 'var(--color-warning-bg)',
    success: 'var(--color-success)',
    successBg: 'var(--color-success-bg)',
  },
  typography: {
    fontHeading: 'var(--font-heading)',
    fontHeadingWeight: 'var(--font-heading-weight)',
    fontBody: 'var(--font-body)',
    fontMono: 'var(--font-mono)',
  },
  shadow: {
    sm: 'var(--shadow-sm)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
    header: 'var(--shadow-header)',
    railActive: 'var(--shadow-rail-active)',
    tableHead: 'var(--shadow-table-head)',
  },
  space: {
    space1: 'var(--space-1)',
    space2: 'var(--space-2)',
    space3: 'var(--space-3)',
    space4: 'var(--space-4)',
    space6: 'var(--space-6)',
    space8: 'var(--space-8)',
    compact1: 'var(--space-compact-1)',
    compact2: 'var(--space-compact-2)',
    compact3: 'var(--space-compact-3)',
    compact4: 'var(--space-compact-4)',
    compact6: 'var(--space-compact-6)',
    compact8: 'var(--space-compact-8)',
  },
  radius: {
    sm: 'var(--radius-sm)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    tag: 'var(--radius-tag)',
    pill: 'var(--radius-pill)',
    full: 'var(--radius-full)',
  },
  zIndex: {
    topbar: 'var(--z-topbar)',
    header: 'var(--z-header)',
    rail: 'var(--z-rail)',
    breadcrumbs: 'var(--z-breadcrumbs)',
    breadcrumb: 'var(--z-breadcrumb)',
    tableHead: 'var(--z-table-head)',
    tableHeader: 'var(--z-table-header)',
    content: 'var(--z-content)',
    base: 'var(--z-base)',
    dropdown: 'var(--z-dropdown)',
    modal: 'var(--z-modal)',
    toast: 'var(--z-toast)',
  },
} as const;

/**
 * Raw Theme Colors for Canvas/SVG/Charts
 */
export const THEME_PALETTE = {
  accent: '#f06311',
  accent700: '#a03d05',
  accent800: '#7a2f04',
  accent2: '#ac803e',
  ink: '#2f353f',
  bg: '#f3f2f2',
  surface: '#eae9e9',
  neutral600: '#7d7979',
} as const;

/**
 * Numeric Layout & Layer Constants
 */
export const LAYOUT_LAYERS = {
  TOPBAR: 6,
  HEADER: 6,
  RAIL: 5,
  BREADCRUMB: 4,
  STICKY_TABLE_HEADER: 3,
  CONTENT: 1,
  DROPDOWN: 20,
  MODAL: 30,
  TOAST: 50,
} as const;

export const BREAKPOINTS = {
  MOBILE_MAX: 860,
  DESKTOP_MIN: 861,
} as const;
