// <auto-generated />
using System;
using Master.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Master.Repository.Migrations.Contacts
{
    [DbContext(typeof(ContactsDbContext))]
    [Migration("20260902151427_InitialContactsSchema")]
    partial class InitialContactsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("con")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Master.Entity.TableEntities.ApiClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("HashedApiKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId", "OrgId");

                    b.ToTable("ApiClients", "con");
                });

            modelBuilder.Entity("Master.Entity.TableEntities.Contact", b =>
                {
                    b.Property<long>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ContactId"));

                    b.Property<string>("ContactCategory")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("ContactCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DefaultPriceListId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("GstRegistrationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Gstin")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCustomer")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsJobWorker")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMsme")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrescriber")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTdsApplicable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVendor")
                        .HasColumnType("boolean");

                    b.Property<string>("LegalName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("MaxDiscountPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("MaxOutstandingDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("Pan")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<long?>("PayableAccountId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PaymentTermId")
                        .HasColumnType("bigint");

                    b.Property<int?>("PlaceOfSupplyStateId")
                        .HasColumnType("integer");

                    b.Property<long?>("ReceivableAccountId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("SubLedgerProvisionedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tan")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TdsSection")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("UdyamNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("ContactId");

                    b.HasIndex("CustomerId", "OrgId");

                    b.HasIndex("OrgId", "ContactCode")
                        .IsUnique();

                    b.HasIndex("OrgId", "ContactId")
                        .HasDatabaseName("IX_Contacts_SubLedgerPending")
                        .HasFilter("\"SubLedgerProvisionedAt\" IS NULL");

                    b.HasIndex("OrgId", "DisplayName");

                    b.HasIndex("OrgId", "Gstin")
                        .IsUnique()
                        .HasDatabaseName("IX_Contacts_Gstin")
                        .HasFilter("\"Gstin\" IS NOT NULL");

                    b.HasIndex(new[] { "OrgId" }, "IX_Contacts_Customer")
                        .HasFilter("\"IsCustomer\" = true");

                    b.HasIndex(new[] { "OrgId" }, "IX_Contacts_JobWorker")
                        .HasFilter("\"IsJobWorker\" = true");

                    b.HasIndex(new[] { "OrgId" }, "IX_Contacts_Prescriber")
                        .HasFilter("\"IsPrescriber\" = true");

                    b.HasIndex(new[] { "OrgId" }, "IX_Contacts_Vendor")
                        .HasFilter("\"IsVendor\" = true");

                    b.ToTable("Contacts", "con", t =>
                        {
                            t.HasCheckConstraint("chk_contact_gstin_registration", "(\"GstRegistrationType\" IN ('Regular', 'Composition', 'Sez') AND \"Gstin\" IS NOT NULL) OR (\"GstRegistrationType\" IN ('Unregistered', 'Overseas', 'Consumer') AND \"Gstin\" IS NULL)");

                            t.HasCheckConstraint("chk_contact_limits", "(\"CreditLimit\" IS NULL OR \"CreditLimit\" >= 0) AND (\"MaxOutstandingDays\" IS NULL OR \"MaxOutstandingDays\" >= 0) AND (\"MaxDiscountPercent\" IS NULL OR (\"MaxDiscountPercent\" >= 0 AND \"MaxDiscountPercent\" <= 100))");

                            t.HasCheckConstraint("chk_contact_msme", "\"IsMsme\" = false OR \"UdyamNumber\" IS NOT NULL");

                            t.HasCheckConstraint("chk_contact_role", "\"IsCustomer\" = true OR \"IsVendor\" = true OR \"IsJobWorker\" = true OR \"IsPrescriber\" = true");

                            t.HasCheckConstraint("chk_contact_tds", "\"IsTdsApplicable\" = false OR \"TdsSection\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Master.Entity.TableEntities.ContactAddress", b =>
                {
                    b.Property<long>("ContactAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ContactAddressId"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("ContactId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContactPersonName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Gstin")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Landmark")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("StateId")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("ContactAddressId");

                    b.HasIndex("ContactId");

                    b.HasIndex("CustomerId", "OrgId");

                    b.HasIndex("OrgId", "ContactId", "AddressType")
                        .IsUnique()
                        .HasDatabaseName("IX_ContactAddresses_Default")
                        .HasFilter("\"IsDefault\" = true");

                    b.ToTable("ContactAddresses", "con");
                });

            modelBuilder.Entity("Master.Entity.TableEntities.ContactAttachment", b =>
                {
                    b.Property<long>("ContactAttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ContactAttachmentId"));

                    b.Property<long>("ContactId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("ContactAttachmentId");

                    b.HasIndex("ContactId");

                    b.HasIndex("CustomerId", "OrgId");

                    b.HasIndex("OrgId", "ContactId");

                    b.HasIndex("OrgId", "StoragePath")
                        .IsUnique()
                        .HasDatabaseName("IX_ContactAttachments_Storage");

                    b.ToTable("ContactAttachments", "con", t =>
                        {
                            t.HasCheckConstraint("chk_attachment_size", "\"FileSizeBytes\" > 0");
                        });
                });

            modelBuilder.Entity("Master.Entity.TableEntities.ContactBankDetail", b =>
                {
                    b.Property<long>("ContactBankDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ContactBankDetailId"));

                    b.Property<string>("AccountHolderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AccountKind")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BranchName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("ContactId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ifsc")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpiId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("ContactBankDetailId");

                    b.HasIndex("ContactId");

                    b.HasIndex("CustomerId", "OrgId");

                    b.HasIndex("OrgId", "ContactId")
                        .IsUnique()
                        .HasDatabaseName("IX_ContactBankDetails_Default")
                        .HasFilter("\"IsDefault\" = true");

                    b.ToTable("ContactBankDetails", "con");
                });

            modelBuilder.Entity("Master.Entity.TableEntities.ContactLicence", b =>
                {
                    b.Property<long>("ContactLicenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ContactLicenceId"));

                    b.Property<long>("ContactId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly?>("ExpiresOn")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("IssuedOn")
                        .HasColumnType("date");

                    b.Property<string>("IssuingAuthority")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LicenceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LicenceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("ContactLicenceId");

                    b.HasIndex("ContactId");

                    b.HasIndex("CustomerId", "OrgId");

                    b.HasIndex("OrgId", "ContactId");

                    b.HasIndex("OrgId", "ExpiresOn")
                        .HasDatabaseName("IX_ContactLicences_Expiry")
                        .HasFilter("\"ExpiresOn\" IS NOT NULL");

                    b.ToTable("ContactLicences", "con", t =>
                        {
                            t.HasCheckConstraint("chk_licence_dates", "\"IssuedOn\" IS NULL OR \"ExpiresOn\" IS NULL OR \"ExpiresOn\" >= \"IssuedOn\"");
                        });
                });

            modelBuilder.Entity("Master.Entity.TableEntities.ContactPerson", b =>
                {
                    b.Property<long>("ContactPersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ContactPersonId"));

                    b.Property<long>("ContactId")
                        .HasColumnType("bigint");

                    b.Property<long>("ContactPersonRoleId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Salutation")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("ContactPersonId");

                    b.HasIndex("ContactId");

                    b.HasIndex("ContactPersonRoleId");

                    b.HasIndex("CustomerId", "OrgId");

                    b.HasIndex("OrgId", "ContactId")
                        .IsUnique()
                        .HasDatabaseName("IX_ContactPersons_Default")
                        .HasFilter("\"IsDefault\" = true");

                    b.HasIndex("OrgId", "Email")
                        .HasDatabaseName("IX_ContactPersons_Email")
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.HasIndex("OrgId", "MobileNumber")
                        .HasDatabaseName("IX_ContactPersons_Mobile")
                        .HasFilter("\"MobileNumber\" IS NOT NULL");

                    b.ToTable("ContactPersons", "con");
                });

            modelBuilder.Entity("Master.Entity.TableEntities.ContactPersonRole", b =>
                {
                    b.Property<long>("ContactPersonRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ContactPersonRoleId"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RoleSystemName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("ContactPersonRoleId");

                    b.HasIndex("OrgId")
                        .IsUnique()
                        .HasDatabaseName("IX_ContactPersonRoles_Default")
                        .HasFilter("\"IsDefault\" = true");

                    b.HasIndex("CustomerId", "OrgId");

                    b.HasIndex("OrgId", "RoleName")
                        .IsUnique();

                    b.HasIndex("OrgId", "RoleSystemName")
                        .IsUnique()
                        .HasDatabaseName("IX_ContactPersonRoles_SystemName")
                        .HasFilter("\"RoleSystemName\" IS NOT NULL");

                    b.HasIndex("OrgId", "DisplayOrder", "RoleName")
                        .HasDatabaseName("IX_ContactPersonRoles_Order");

                    b.ToTable("ContactPersonRoles", "con");
                });

            modelBuilder.Entity("Shared.Kernel.Numbering.NumberingSeries", b =>
                {
                    b.Property<long>("NumberingSeriesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("NumberingSeriesId"));

                    b.Property<bool>("AllowManualOverride")
                        .HasColumnType("boolean");

                    b.Property<string>("BranchCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("FinancialYearFormat")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<bool>("IncludeBranchCode")
                        .HasColumnType("boolean");

                    b.Property<bool>("IncludeFinancialYear")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("LastResetOn")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<long>("NextNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("NumberLength")
                        .HasColumnType("integer");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<string>("Prefix")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("ResetFrequency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Separator")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<string>("SeriesCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("SeriesFor")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("SeriesName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SeriesSystemName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<long>("StartNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Suffix")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("NumberingSeriesId");

                    b.HasIndex("CustomerId", "OrgId");

                    b.HasIndex("OrgId", "SeriesCode")
                        .IsUnique()
                        .HasDatabaseName("IX_NumberingSeries_Default")
                        .HasFilter("\"IsDefault\" = true");

                    b.HasIndex("OrgId", "SeriesName")
                        .IsUnique();

                    b.HasIndex("OrgId", "SeriesSystemName")
                        .IsUnique()
                        .HasDatabaseName("IX_NumberingSeries_SystemName")
                        .HasFilter("\"SeriesSystemName\" IS NOT NULL");

                    b.HasIndex("OrgId", "DisplayOrder", "SeriesName")
                        .HasDatabaseName("IX_NumberingSeries_Order");

                    b.ToTable("NumberingSeries", "acc", t =>
                        {
                            t.ExcludeFromMigrations();

                            t.HasCheckConstraint("chk_numbering_branch_code", "\"IncludeBranchCode\" = false OR \"BranchCode\" IS NOT NULL");

                            t.HasCheckConstraint("chk_numbering_counter", "\"NextNumber\" >= \"StartNumber\" AND \"NumberLength\" BETWEEN 1 AND 12");

                            t.HasCheckConstraint("chk_numbering_manual_override", "\"SeriesFor\" = 'Master' OR \"AllowManualOverride\" = false");
                        });
                });

            modelBuilder.Entity("Master.Entity.TableEntities.ContactAddress", b =>
                {
                    b.HasOne("Master.Entity.TableEntities.Contact", null)
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Master.Entity.TableEntities.ContactAttachment", b =>
                {
                    b.HasOne("Master.Entity.TableEntities.Contact", null)
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Master.Entity.TableEntities.ContactBankDetail", b =>
                {
                    b.HasOne("Master.Entity.TableEntities.Contact", null)
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Master.Entity.TableEntities.ContactLicence", b =>
                {
                    b.HasOne("Master.Entity.TableEntities.Contact", null)
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Master.Entity.TableEntities.ContactPerson", b =>
                {
                    b.HasOne("Master.Entity.TableEntities.Contact", null)
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Master.Entity.TableEntities.ContactPersonRole", null)
                        .WithMany()
                        .HasForeignKey("ContactPersonRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
